---
title: "Causal Inference in R"
author:  "Malcolm Barrett, Lucy D'Agostino McGowan, Travis Gerke"
date: "`r Sys.Date()`"
output: 
  bookdown::gitbook:
    css: style.css
documentclass: book
biblio-style: apalike
bibliography: citations.bib
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
site: bookdown::bookdown_site
description: > 
  This book covers causal inference techniques to help statisticians, epidemiologists, economists, and data scientists implement best practices using R.
github-repo: malcolmbarrett/causal-inference-in-r
graphics: yes
# Render with:
# bookdown::render_book(output_format = bookdown::pdf_book())
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  dev = "ragg_png",
  dpi = 320, 
  out.width = "80%",
  fig.width = 6,
  fig.asp = 0.618,
  fig.retina = 2,
  fig.align = "center",
  fig.show = "hold"
)

options(
  tidyverse.quiet = TRUE, 
  htmltools.dir.version = FALSE, 
  formatR.indent = 2, 
  width = 55, 
  digits = 4
)
```

```{r child = 'frontmatter/preface.Rmd'}

```

```{r child = 'chapters/chapter-01.Rmd'}
```

```{r child = 'chapters/chapter-02.Rmd'}
```

```{r child = 'chapters/chapter-03.Rmd'}
```

```{r child = 'chapters/chapter-06.Rmd'}
```
