{
  "hash": "e3c60b0eddf12af85ad025f1e4a019b1",
  "result": {
    "markdown": "# Preparing data to answer causal questions {#sec-data-causal}\n\n\n\n\n\n## Introduction to the data {#sec-data}\n\nThroughout this book we will be using data obtained from [Touring Plans](https://touringplans.com).\nTouring Plans is a company that helps folks plan their trips to Disney and Universal theme parks.\nOne of their goals is to accurately predict attraction wait times at these theme parks by leveraging data and statistical modeling.\nThe `{touringplans}` R package includes several datasets containing information about Disney theme park attractions.\nA summary of the attractions included in the package can be found by running the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(touringplans)\nattractions_metadata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 8\n   dataset_name name  short_name park  land  opened_on \n   <chr>        <chr> <chr>      <chr> <chr> <date>    \n 1 alien_sauce… Alie… Alien Sau… Disn… Toy … 2018-06-30\n 2 dinosaur     DINO… DINOSAUR   Disn… Dino… 1998-04-22\n 3 expedition_… Expe… Expeditio… Disn… Asia  2006-04-07\n 4 flight_of_p… Avat… Flight of… Disn… Pand… 2017-05-27\n 5 kilimanjaro… Kili… Kilimanja… Disn… Afri… 1998-04-22\n 6 navi_river   Na'v… Na'vi Riv… Disn… Pand… 2017-05-27\n 7 pirates_of_… Pira… Pirates o… Magi… Adve… 1973-12-17\n 8 rock_n_roll… Rock… Rock Coas… Disn… Suns… 1999-07-29\n 9 seven_dwarf… Seve… 7 Dwarfs … Magi… Fant… 2014-05-28\n10 slinky_dog   Slin… Slinky Dog Disn… Toy … 2018-06-30\n11 soarin       Soar… Soarin'    Epcot Worl… 2005-05-05\n12 spaceship_e… Spac… Spaceship… Epcot Worl… 1982-10-01\n13 splash_moun… Spla… Splash Mo… Magi… Fron… 1992-07-17\n14 toy_story_m… Toy … Toy Story… Disn… Toy … 2008-05-31\n# ℹ 2 more variables: duration <dbl>,\n#   average_wait_per_hundred <dbl>\n```\n\n\n:::\n:::\n\n\nAdditionally, this package contains a dataset with raw metadata about the parks, with observations recorded daily.\nThis metadata includes information like the Walt Disney World ticket season on the particular day (was it high season -- think Christmas -- or low season -- think right when school started), what the historic temperatures were in the park on that day, and whether there was a special event, such as \"extra magic hours\" in the park on that day (did the park open early to guests staying in the Walt Disney World resorts?).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks_metadata_raw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,079 × 181\n   date       wdw_ticket_season dayofweek dayofyear\n   <date>     <chr>                 <dbl>     <dbl>\n 1 2015-01-01 <NA>                      5         0\n 2 2015-01-02 <NA>                      6         1\n 3 2015-01-03 <NA>                      7         2\n 4 2015-01-04 <NA>                      1         3\n 5 2015-01-05 <NA>                      2         4\n 6 2015-01-06 <NA>                      3         5\n 7 2015-01-07 <NA>                      4         6\n 8 2015-01-08 <NA>                      5         7\n 9 2015-01-09 <NA>                      6         8\n10 2015-01-10 <NA>                      7         9\n# ℹ 2,069 more rows\n# ℹ 177 more variables: weekofyear <dbl>,\n#   monthofyear <dbl>, year <dbl>, season <chr>,\n#   holidaypx <dbl>, holidaym <dbl>, holidayn <chr>,\n#   holiday <dbl>, wdwticketseason <chr>,\n#   wdwracen <chr>, wdweventn <chr>, wdwevent <dbl>,\n#   wdwrace <dbl>, wdwseason <chr>, …\n```\n\n\n:::\n:::\n\n\nSuppose the causal question of interest is:\n\n**Is there a relationship between whether there were \"Extra Magic Hours\" in the morning at Magic Kingdom and the average wait time for an attraction called the \"Seven Dwarfs Mine Train\" the same day between 9am and 10am in 2018?**\n\nLet's begin by diagramming this causal question (@fig-seven-diag).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagram of the causal question \"Is there a relationship between whether there were \"Extra Magic Hours\" in the morning at Magic Kingdom and the average wait time for an attraction called the \"Seven Dwarfs Mine Train\" the same day between 9am and 10am in 2018?\"](07-prep-data_files/figure-html/fig-seven-diag-1.png){#fig-seven-diag width=672}\n:::\n:::\n\n\nHistorically, guests who stayed in a Walt Disney World resort hotel could access the park during \"Extra Magic Hours,\" during which the park was closed to all other guests.\nThese extra hours could be in the morning or evening.\nThe Seven Dwarfs Mine Train is a ride at Walt Disney World's Magic Kingdom.\nMagic Kingdom may or may not be selected each day to have these \"Extra Magic Hours.\" We are interested in examining the relationship between whether there were \"Extra Magic Hours\" in the morning and the average wait time for the Seven Dwarfs Mine Train on the same day between 9 am and 10 am.\nBelow is a proposed DAG for this question.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Proposed DAG for the relationship between Extra Magic Hours in the morning at a particular park and the average wait time between 9 am and 10 am. Here we are saying that we believe 1) Extra Magic Hours impacts average wait time and 2) both Extra Magic Hours and average wait time are determined by the time the park closes, historic high temperatures, and ticket season.](07-prep-data_files/figure-html/fig-dag-magic-1.png){#fig-dag-magic width=672}\n:::\n:::\n\n\nSince we are not in charge of Walt Disney World's operations, we cannot randomize dates to have (or not) \"Extra Magic Hours\", therefore, we need to rely on previously collected observational data and do our best to emulate the *target trial* that we would have created, should it have been possible.\nHere, our observations are *days*.\nLooking at the diagram above, we can map each element of the causal question to elements of our target trial protocol:\n\n-   **Eligibility criteria**: Days must be from 2018\n-   **Exposure definition**: Magic kingdom had \"Extra Magic Hours\" in the morning\n-   **Assignment procedures**: Observed -- if the historic data suggests there were \"Extra Magic Hours\" in the morning on a particular day, that day is classified as \"exposed\" otherwise it is \"unexposed\"\n-   **Follow-up period**: From park open to 10am.\n-   **Outcome definition**: The average posted wait time between 9am and 10am\n-   **Causal contrast of interest**: Average treatment effect (we will discuss this in @sec-estimands)\n-   **Analysis plan**: We use inverse probability waiting after fitting a propensity score model to estimate the average treatment effect of the exposure on the outcome of interest. We will adjust for variables as determined by our DAG (@fig-dag-magic)\n\n## Data wrangling and recipes\n\nMost of our data manipulation tools come from the `{dplyr}` package (@tbl-dplyr).\nWe will also use `{lubridate}` to help us manipulate dates.\n\n| Target trial protocol element | {dplyr} functions                           |\n|-------------------------------|---------------------------------------------|\n| Eligibility criteria          | `filter()`                                  |\n| Exposure definition           | `mutate()`                                  |\n| Assignment procedures         | `mutate()`                                  |\n| Follow-up period              | `mutate()` `pivot_longer()` `pivot_wider()` |\n| Outcome definition            | `mutate()`                                  |\n| Analysis plan                 | `select()` `mutate()`                       |\n\n: Mapping target trial protocol elements to commonly used `{dplyr}` functions {#tbl-dplyr}\n\nTo answer this question, we are going to need to manipulate both the `seven_dwarfs_train` dataset as well as the `parks_metadata_raw` dataset.\nLet's start with the `seven_dwarfs_train` data set.\nThe Seven Dwarfs Mine Train ride is an attraction at Walt Disney World's Magic Kingdom.\nThe `seven_dwarfs_train` dataset in the {touringplans} package contains information about the date a particular wait time was recorded (`park_date`), the time of the wait time (`wait_datetime`), the actual wait time (`wait_minutes_actual`), and the posted wait time (`wait_minutes_posted`).\nLet's take a look at this dataset.\nThe {skimr} package is great for getting a quick glimpse at a new dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(skimr)\nskim(seven_dwarfs_train)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                   |\n|:------------------------|:------------------|\n|Name                     |seven_dwarfs_train |\n|Number of rows           |321631             |\n|Number of columns        |4                  |\n|_______________________  |                   |\n|Column type frequency:   |                   |\n|Date                     |1                  |\n|numeric                  |2                  |\n|POSIXct                  |1                  |\n|________________________ |                   |\n|Group variables          |None               |\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|park_date     |         0|             1|2015-01-01 |2021-12-28 |2018-04-07 |     2334|\n\n\n**Variable type: numeric**\n\n|skim_variable       | n_missing| complete_rate|  mean|      sd|     p0| p25| p50| p75| p100|hist  |\n|:-------------------|---------:|-------------:|-----:|-------:|------:|---:|---:|---:|----:|:-----|\n|wait_minutes_actual |    313996|          0.02| 23.99| 1064.06| -92918|  21|  31|  46|  217|▁▁▁▁▇ |\n|wait_minutes_posted |     30697|          0.90| 76.96|   33.99|      0|  50|  70|  95|  300|▆▇▁▁▁ |\n\n\n**Variable type: POSIXct**\n\n|skim_variable | n_missing| complete_rate|min                 |max                 |median              | n_unique|\n|:-------------|---------:|-------------:|:-------------------|:-------------------|:-------------------|--------:|\n|wait_datetime |         0|             1|2015-01-01 07:51:12 |2021-12-28 22:57:34 |2018-04-07 23:14:06 |   321586|\n\n\n:::\n:::\n\n\nExamining the output above, we learn that this dataset contains four columns and 321,631 rows.\nWe also learn that the dates span from 2015 to 2021.\nWe can also examine the distribution of each of the variables to detect any potential anomalies.\nNotice anything strange?\nLook at the `p0` (that is the minimum value) for `wait_minutes_actual`.\nIt is `-92918`!\nWe are not using this variable for this analysis, but we will for future analyses, so this is good to keep in mind.\n\nWe need this dataset to calculate our *outcome*.\nRecall from above that our outcome is defined as the average posted wait time between 9am and 10am.\nAdditionally, recall our eligibility criteria states that we need to restrict our analysis to days in 2018.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(lubridate)\nseven_dwarfs_train_2018 <- seven_dwarfs_train |>\n  filter(year(park_date) == 2018) |> # eligibility criteria\n  mutate(hour = hour(wait_datetime)) |> # get hour from wait\n  group_by(park_date, hour) |> # group by date\n  summarise(\n    wait_minutes_posted_avg = mean(wait_minutes_posted, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |> # get average wait time\n  mutate(\n    wait_minutes_posted_avg =\n      case_when(\n        is.nan(wait_minutes_posted_avg) ~ NA,\n        TRUE ~ wait_minutes_posted_avg\n      )\n  ) |> # if it is NAN make it NA\n  filter(hour == 9) # only keep the average wait time between 9 and 10\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nseven_dwarfs_train_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 362 × 3\n   park_date   hour wait_minutes_posted_avg\n   <date>     <int>                   <dbl>\n 1 2018-01-01     9                    60  \n 2 2018-01-02     9                    60  \n 3 2018-01-03     9                    60  \n 4 2018-01-04     9                    68.9\n 5 2018-01-05     9                    70.6\n 6 2018-01-06     9                    33.3\n 7 2018-01-07     9                    46.4\n 8 2018-01-08     9                    69.5\n 9 2018-01-09     9                    64.3\n10 2018-01-10     9                    74.3\n# ℹ 352 more rows\n```\n\n\n:::\n:::\n\n\nNow that we have our outcome settled, we need to get our exposure variable, as well as any other park-specific variables about the day in question that may be used as variables that we adjust for.\nExamining @fig-dag-magic, we see that we need data for three proposed confounders: the ticket season, the time the park closed, and the historic high temperature.\nThese are in the `parks_metadata_raw` dataset.\nThis data will require extra cleaning, since the names are in the original format.\n\n::: callout-tip\nWe like to have our variable names follow a clean convention -- one way to do this is to follow Emily Riederer's \"Column Names as Contracts\" format [@Riederer_2020].\nThe basic idea is to predefine a set of words, phrases, or stubs with clear meanings to index information, and use these consistently when naming variables.\nFor example, in these data, variables that are specific to a particular wait time are prepended with the term `wait` (e.g. `wait_datetime` and `wait_minutes_actual`), variables that are specific to the park on a particular day, acquired from parks metadata, are prepended with the term `park` (e.g. `park_date` or `park_temperature_high`).\n:::\n\nLet's first decide what variables we will need.\nIn practice, this decision may involve an iterative process.\nFor example, after drawing our DAG or after conducting diagnostic, we may determine that we need more variables than what we originally cleaned.\nLet's start by skimming this dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(parks_metadata_raw)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                   |\n|:------------------------|:------------------|\n|Name                     |parks_metadata_raw |\n|Number of rows           |2079               |\n|Number of columns        |181                |\n|_______________________  |                   |\n|Column type frequency:   |                   |\n|character                |42                 |\n|Date                     |1                  |\n|difftime                 |46                 |\n|logical                  |6                  |\n|numeric                  |86                 |\n|________________________ |                   |\n|Group variables          |None               |\n\n\n**Variable type: character**\n\n|skim_variable         | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:---------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|wdw_ticket_season     |       861|          0.59|   4|   7|     0|        3|          0|\n|season                |       253|          0.88|   4|  29|     0|       17|          0|\n|holidayn              |      1865|          0.10|   3|   7|     0|       43|          0|\n|wdwticketseason       |       761|          0.63|   4|   7|     0|        3|          0|\n|wdwracen              |      1992|          0.04|   4|   6|     0|        5|          0|\n|wdweventn             |      1832|          0.12|   3|  12|     0|        8|          0|\n|wdwseason             |        87|          0.96|   4|  29|     0|       17|          0|\n|mkeventn              |      1546|          0.26|   3|  11|     0|       10|          0|\n|epeventn              |       868|          0.58|   4|   5|     0|        4|          0|\n|hseventn              |      1877|          0.10|   4|   7|     0|        5|          0|\n|akeventn              |      2010|          0.03|   4|   4|     0|        2|          0|\n|holidayj              |      2037|          0.02|   5|  15|     0|        8|          0|\n|insession             |       105|          0.95|   2|   3|     0|       95|          0|\n|insession_enrollment  |       105|          0.95|   2|   4|     0|      100|          0|\n|insession_wdw         |       105|          0.95|   2|   4|     0|       94|          0|\n|insession_dlr         |       105|          0.95|   2|   4|     0|       94|          0|\n|insession_sqrt_wdw    |       105|          0.95|   2|   4|     0|       97|          0|\n|insession_sqrt_dlr    |       105|          0.95|   2|   4|     0|       97|          0|\n|insession_california  |       105|          0.95|   2|   4|     0|       89|          0|\n|insession_dc          |       105|          0.95|   2|   4|     0|       86|          0|\n|insession_central_fl  |       105|          0.95|   2|   4|     0|       71|          0|\n|insession_drive1_fl   |       105|          0.95|   2|   4|     0|       85|          0|\n|insession_drive2_fl   |       105|          0.95|   2|   4|     0|       95|          0|\n|insession_drive_ca    |       105|          0.95|   2|   4|     0|       91|          0|\n|insession_florida     |       105|          0.95|   2|   4|     0|       86|          0|\n|insession_mardi_gras  |       105|          0.95|   2|   4|     0|       82|          0|\n|insession_midwest     |       105|          0.95|   2|   4|     0|       75|          0|\n|insession_ny_nj       |       105|          0.95|   2|   4|     0|        8|          0|\n|insession_ny_nj_pa    |       105|          0.95|   2|   4|     0|       19|          0|\n|insession_new_england |       105|          0.95|   2|   4|     0|       45|          0|\n|insession_new_jersey  |       105|          0.95|   2|   4|     0|        2|          0|\n|insession_nothwest    |       105|          0.95|   2|   4|     0|       17|          0|\n|insession_planes      |       105|          0.95|   2|   4|     0|       81|          0|\n|insession_socal       |       105|          0.95|   2|   4|     0|       80|          0|\n|insession_southwest   |       105|          0.95|   2|   4|     0|       86|          0|\n|mkprddn               |       183|          0.91|  33|  41|     0|        2|          0|\n|mkprdnn               |      1358|          0.35|  29|  38|     0|        2|          0|\n|mkfiren               |       134|          0.94|  18|  65|     0|        8|          0|\n|epfiren               |       126|          0.94|  13|  35|     0|        2|          0|\n|hsfiren               |       485|          0.77|  24|  66|     0|        6|          0|\n|hsshwnn               |       164|          0.92|  10|  28|     0|        2|          0|\n|akshwnn               |       883|          0.58|  15|  33|     0|        2|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|2015-01-01 |2021-08-31 |2017-11-05 |     2079|\n\n\n**Variable type: difftime**\n\n|skim_variable | n_missing| complete_rate|min        |max         |median   | n_unique|\n|:-------------|---------:|-------------:|:----------|:-----------|:--------|--------:|\n|mkopen        |         0|          1.00|21600 secs |32400 secs  |09:00:00 |        4|\n|mkclose       |         0|          1.00|54000 secs |107940 secs |22:00:00 |       13|\n|mkemhopen     |         0|          1.00|21600 secs |32400 secs  |09:00:00 |        5|\n|mkemhclose    |         0|          1.00|54000 secs |107940 secs |23:00:00 |       14|\n|mkopenyest    |         0|          1.00|21600 secs |32400 secs  |09:00:00 |        4|\n|mkcloseyest   |         0|          1.00|54000 secs |107940 secs |22:00:00 |       13|\n|mkopentom     |         0|          1.00|21600 secs |32400 secs  |09:00:00 |        4|\n|mkclosetom    |         0|          1.00|54000 secs |107940 secs |22:00:00 |       13|\n|epopen        |         0|          1.00|25200 secs |43200 secs  |09:00:00 |        6|\n|epclose       |         0|          1.00|61200 secs |90000 secs  |21:00:00 |        9|\n|epemhopen     |         0|          1.00|25200 secs |43200 secs  |09:00:00 |        6|\n|epemhclose    |         0|          1.00|61200 secs |90000 secs  |21:00:00 |       12|\n|epopenyest    |         0|          1.00|25200 secs |43200 secs  |09:00:00 |        6|\n|epcloseyest   |         0|          1.00|61200 secs |90000 secs  |21:00:00 |        9|\n|epopentom     |         0|          1.00|25200 secs |43200 secs  |09:00:00 |        6|\n|epclosetom    |         0|          1.00|61200 secs |90000 secs  |21:00:00 |        9|\n|hsopen        |         0|          1.00|21600 secs |36000 secs  |09:00:00 |        6|\n|hsclose       |         0|          1.00|50400 secs |86400 secs  |21:00:00 |       14|\n|hsemhopen     |         0|          1.00|21600 secs |36000 secs  |09:00:00 |        7|\n|hsemhclose    |         0|          1.00|50400 secs |93600 secs  |21:00:00 |       18|\n|hsopenyest    |         0|          1.00|21600 secs |36000 secs  |09:00:00 |        6|\n|hscloseyest   |         0|          1.00|50400 secs |86400 secs  |21:00:00 |       14|\n|hsopentom     |         0|          1.00|21600 secs |36000 secs  |09:00:00 |        6|\n|hsclosetom    |         0|          1.00|50400 secs |86400 secs  |21:00:00 |       14|\n|akopen        |         0|          1.00|25200 secs |32400 secs  |09:00:00 |        3|\n|akclose       |         0|          1.00|50400 secs |86400 secs  |20:00:00 |       16|\n|akemhopen     |         0|          1.00|25200 secs |32400 secs  |09:00:00 |        3|\n|akemhclose    |         0|          1.00|50400 secs |90000 secs  |20:00:00 |       17|\n|akopenyest    |         0|          1.00|25200 secs |32400 secs  |09:00:00 |        3|\n|akcloseyest   |         0|          1.00|50400 secs |86400 secs  |20:00:00 |       16|\n|akopentom     |         0|          1.00|25200 secs |32400 secs  |09:00:00 |        3|\n|akclosetom    |         0|          1.00|50400 secs |86400 secs  |20:00:00 |       16|\n|mkprddt1      |       183|          0.91|39600 secs |61200 secs  |15:00:00 |        5|\n|mkprddt2      |      1851|          0.11|50400 secs |73800 secs  |15:30:00 |        5|\n|mkprdnt1      |      1358|          0.35|68400 secs |82800 secs  |21:00:00 |       11|\n|mkprdnt2      |      1480|          0.29|0 secs     |84600 secs  |23:00:00 |        8|\n|mkfiret1      |       134|          0.94|66600 secs |80100 secs  |21:15:00 |       12|\n|mkfiret2      |      2069|          0.00|85800 secs |85800 secs  |23:50:00 |        1|\n|epfiret1      |       126|          0.94|64800 secs |81000 secs  |21:00:00 |        6|\n|epfiret2      |      2074|          0.00|85200 secs |85200 secs  |23:40:00 |        1|\n|hsfiret1      |       485|          0.77|0 secs     |82800 secs  |21:00:00 |       17|\n|hsfiret2      |      2045|          0.02|0 secs     |81000 secs  |21:00:00 |        5|\n|hsshwnt1      |       164|          0.92|65100 secs |79200 secs  |20:30:00 |       10|\n|hsshwnt2      |      1369|          0.34|72000 secs |82800 secs  |21:30:00 |       11|\n|akshwnt1      |       883|          0.58|65700 secs |76500 secs  |20:30:00 |       13|\n|akshwnt2      |      1149|          0.45|70200 secs |81000 secs  |21:45:00 |       13|\n\n\n**Variable type: logical**\n\n|skim_variable | n_missing| complete_rate| mean|count |\n|:-------------|---------:|-------------:|----:|:-----|\n|hsprddt1      |      2079|             0|  NaN|:     |\n|hsprddn       |      2079|             0|  NaN|:     |\n|akprddt1      |      2079|             0|  NaN|:     |\n|akprddt2      |      2079|             0|  NaN|:     |\n|akprddn       |      2079|             0|  NaN|:     |\n|akfiren       |      2079|             0|  NaN|:     |\n\n\n**Variable type: numeric**\n\n|skim_variable      | n_missing| complete_rate|        mean|         sd|          p0|         p25|         p50|         p75|        p100|hist  |\n|:------------------|---------:|-------------:|-----------:|----------:|-----------:|-----------:|-----------:|-----------:|-----------:|:-----|\n|dayofweek          |         0|             1|        4.00|       2.00|        1.00|        2.00|        4.00|        6.00|        7.00|▇▃▃▃▇ |\n|dayofyear          |         0|             1|      181.84|     106.34|        0.00|       89.00|      184.00|      273.00|      365.00|▇▇▇▇▇ |\n|weekofyear         |         0|             1|       26.09|      15.20|        0.00|       13.00|       26.00|       39.00|       53.00|▇▇▇▇▇ |\n|monthofyear        |         0|             1|        6.51|       3.48|        1.00|        3.00|        7.00|       10.00|       12.00|▇▅▆▅▇ |\n|year               |         0|             1|     2017.41|       1.74|     2015.00|     2016.00|     2017.00|     2019.00|     2021.00|▇▃▃▃▃ |\n|holidaypx          |         0|             1|        7.85|       6.89|        0.00|        3.00|        6.00|       10.00|       33.00|▇▅▂▁▁ |\n|holidaym           |         0|             1|        0.54|       1.35|        0.00|        0.00|        0.00|        0.00|        5.00|▇▁▁▁▁ |\n|holiday            |         0|             1|        0.10|       0.30|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|wdwevent           |         0|             1|        0.12|       0.32|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|wdwrace            |         0|             1|        0.04|       0.20|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|wdwmaxtemp         |         5|             1|       82.80|       8.53|       51.11|       78.29|       84.50|       89.54|       97.72|▁▁▃▇▆ |\n|wdwmintemp         |         6|             1|       65.50|      10.18|       27.48|       59.03|       68.35|       74.10|       81.28|▁▂▃▆▇ |\n|wdwmeantemp        |         6|             1|       74.15|       9.06|       39.75|       68.76|       76.37|       81.61|       87.76|▁▂▃▆▇ |\n|mkevent            |         0|             1|        0.26|       0.44|        0.00|        0.00|        0.00|        1.00|        1.00|▇▁▁▁▃ |\n|epevent            |         0|             1|        0.58|       0.49|        0.00|        0.00|        1.00|        1.00|        1.00|▆▁▁▁▇ |\n|hsevent            |         0|             1|        0.10|       0.30|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|akevent            |         0|             1|        0.03|       0.18|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|mkemhmorn          |         0|             1|        0.19|       0.40|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|mkemhmyest         |         0|             1|        0.19|       0.40|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|mkemhmtom          |         0|             1|        0.19|       0.40|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|mkemheve           |         0|             1|        0.13|       0.33|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|mkhoursemh         |         0|             1|       13.64|       1.98|        7.50|       13.00|       14.00|       15.00|       23.98|▁▇▅▁▁ |\n|mkhoursemhyest     |         0|             1|       13.65|       1.98|        7.50|       13.00|       14.00|       15.00|       23.98|▁▇▅▁▁ |\n|mkhoursemhtom      |         0|             1|       13.64|       1.98|        7.50|       13.00|       14.00|       15.00|       23.98|▁▇▅▁▁ |\n|mkemheyest         |         0|             1|        0.13|       0.33|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|mkemhetom          |         0|             1|        0.13|       0.33|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemhmorn          |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemhmyest         |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemhmtom          |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemheve           |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemheyest         |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|epemhetom          |         0|             1|        0.13|       0.34|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|ephoursemh         |         0|             1|       12.41|       0.96|        9.00|       12.00|       12.00|       13.00|       17.00|▁▇▃▂▁ |\n|ephoursemhyest     |         0|             1|       12.41|       0.96|        9.00|       12.00|       12.00|       13.00|       17.00|▁▇▃▂▁ |\n|ephoursemhtom      |         0|             1|       12.41|       0.96|        9.00|       12.00|       12.00|       13.00|       17.00|▁▇▃▂▁ |\n|hsemhmorn          |         0|             1|        0.18|       0.38|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|hsemhmyest         |         0|             1|        0.18|       0.38|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|hsemhmtom          |         0|             1|        0.18|       0.38|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▂ |\n|hsemheve           |         0|             1|        0.06|       0.25|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|hsemheyest         |         0|             1|        0.06|       0.25|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|hsemhetom          |         0|             1|        0.06|       0.25|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|hshoursemh         |         0|             1|       12.32|       1.49|        8.00|       11.00|       12.00|       13.00|       18.00|▁▇▇▂▁ |\n|hshoursemhyest     |         0|             1|       12.32|       1.49|        8.00|       11.00|       12.00|       13.00|       18.00|▁▇▇▂▁ |\n|hshoursemhtom      |         0|             1|       12.32|       1.49|        8.00|       11.00|       12.00|       13.00|       18.00|▁▇▇▂▁ |\n|akemhmorn          |         0|             1|        0.30|       0.46|        0.00|        0.00|        0.00|        1.00|        1.00|▇▁▁▁▃ |\n|akemhmyest         |         0|             1|        0.30|       0.46|        0.00|        0.00|        0.00|        1.00|        1.00|▇▁▁▁▃ |\n|akemhmtom          |         0|             1|        0.30|       0.46|        0.00|        0.00|        0.00|        1.00|        1.00|▇▁▁▁▃ |\n|akemheve           |         0|             1|        0.04|       0.20|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|akemheyest         |         0|             1|        0.04|       0.20|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|akemhetom          |         0|             1|        0.04|       0.20|        0.00|        0.00|        0.00|        0.00|        1.00|▇▁▁▁▁ |\n|akhoursemh         |         0|             1|       11.77|       1.80|        7.00|       11.00|       12.00|       13.00|       17.00|▂▇▇▅▁ |\n|akhoursemhyest     |         0|             1|       11.77|       1.80|        7.00|       11.00|       12.00|       13.00|       17.00|▂▇▇▅▁ |\n|akhoursemhtom      |         0|             1|       11.76|       1.80|        7.00|       11.00|       12.00|       13.00|       17.00|▂▇▇▅▁ |\n|mkhours            |         0|             1|       13.26|       2.01|        7.00|       12.00|       13.00|       15.00|       23.98|▂▇▇▁▁ |\n|mkhoursyest        |         0|             1|       13.26|       2.01|        7.00|       12.00|       13.00|       15.00|       23.98|▂▇▇▁▁ |\n|mkhourstom         |         0|             1|       13.26|       2.00|        7.00|       12.00|       13.00|       15.00|       23.98|▂▇▇▁▁ |\n|ephours            |         0|             1|       12.02|       0.64|        8.00|       12.00|       12.00|       12.00|       17.00|▁▁▇▁▁ |\n|ephoursyest        |         0|             1|       12.03|       0.64|        8.00|       12.00|       12.00|       12.00|       17.00|▁▁▇▁▁ |\n|ephourstom         |         0|             1|       12.02|       0.64|        8.00|       12.00|       12.00|       12.00|       17.00|▁▁▇▁▁ |\n|hshours            |         0|             1|       11.92|       1.19|        5.00|       11.00|       12.00|       12.50|       18.00|▁▁▇▂▁ |\n|hshoursyest        |         0|             1|       11.93|       1.20|        5.00|       11.00|       12.00|       12.50|       18.00|▁▁▇▂▁ |\n|hshourstom         |         0|             1|       11.92|       1.19|        5.00|       11.00|       12.00|       12.50|       18.00|▁▁▇▂▁ |\n|akhours            |         0|             1|       11.46|       1.68|        6.00|       10.50|       11.00|       12.50|       17.00|▁▃▇▃▁ |\n|akhoursyest        |         0|             1|       11.47|       1.68|        6.00|       10.50|       11.00|       12.50|       17.00|▁▃▇▃▁ |\n|akhourstom         |         0|             1|       11.46|       1.68|        6.00|       10.50|       11.00|       12.50|       17.00|▁▃▇▃▁ |\n|weather_wdwhigh    |         0|             1|       82.35|       7.86|       70.20|       74.60|       82.80|       90.60|       92.30|▅▃▂▂▇ |\n|weather_wdwlow     |         0|             1|       64.10|       9.26|       49.20|       55.80|       63.60|       74.00|       76.10|▅▅▃▂▇ |\n|weather_wdwprecip  |         0|             1|        0.15|       0.08|        0.03|        0.08|        0.12|        0.23|        0.35|▇▆▃▅▁ |\n|capacitylost_mk    |         0|             1|   422110.61|   36458.81|   352865.00|   385812.00|   433857.00|   456055.00|   473553.00|▅▂▁▇▆ |\n|capacitylost_ep    |         0|             1|   366897.04|   24019.96|   325168.00|   338367.00|   380763.00|   381963.00|   394662.00|▅▁▁▂▇ |\n|capacitylost_hs    |         0|             1|   287485.76|   33198.89|   203780.00|   279573.00|   301871.00|   311870.00|   321869.00|▂▁▁▁▇ |\n|capacitylost_ak    |         0|             1|   228193.83|   14967.82|   210779.00|   220778.00|   223178.00|   232777.00|   273873.00|▇▅▁▁▂ |\n|capacitylostwgt_mk |         0|             1| 41374025.71| 3621097.96| 34661635.00| 37641738.00| 42585643.00| 44577245.00| 46545047.00|▅▂▂▇▆ |\n|capacitylostwgt_ep |         0|             1| 35344939.61| 2201138.89| 31692832.00| 32692333.00| 36666337.00| 36668737.00| 37678138.00|▅▁▁▁▇ |\n|capacitylostwgt_hs |         0|             1| 27528647.53| 3049291.37| 19812520.00| 26772627.00| 28771129.00| 29761030.00| 30750931.00|▂▁▁▁▇ |\n|capacitylostwgt_ak |         0|             1| 22386447.82| 1398263.45| 20790321.00| 21780222.00| 21799422.00| 22780123.00| 26739827.00|▇▅▁▁▂ |\n|mkprdday           |         0|             1|        1.07|       0.59|        0.00|        1.00|        1.00|        1.00|        3.00|▁▇▁▁▁ |\n|mkprdngt           |         0|             1|        0.64|       0.90|        0.00|        0.00|        0.00|        2.00|        3.00|▇▁▁▃▁ |\n|mkfirewk           |         0|             1|        0.94|       0.26|        0.00|        1.00|        1.00|        1.00|        2.00|▁▁▇▁▁ |\n|epfirewk           |         0|             1|        0.94|       0.25|        0.00|        1.00|        1.00|        1.00|        3.00|▁▇▁▁▁ |\n|hsprdday           |         0|             1|        0.00|       0.00|        0.00|        0.00|        0.00|        0.00|        0.00|▁▁▇▁▁ |\n|hsfirewk           |         0|             1|        0.78|       0.45|        0.00|        1.00|        1.00|        1.00|        2.00|▂▁▇▁▁ |\n|hsshwngt           |         0|             1|        1.28|       0.62|        0.00|        1.00|        1.00|        2.00|        3.00|▁▇▁▅▁ |\n|hsfirewks          |         0|             1|        1.00|       0.00|        1.00|        1.00|        1.00|        1.00|        1.00|▁▁▇▁▁ |\n|akprdday           |         0|             1|        0.00|       0.00|        0.00|        0.00|        0.00|        0.00|        0.00|▁▁▇▁▁ |\n|akshwngt           |         0|             1|        1.04|       0.97|        0.00|        0.00|        1.00|        2.00|        3.00|▇▂▁▇▁ |\n\n\n:::\n:::\n\n\nThis dataset contains many more variables than the one we worked with previously.\nFor this analysis, we are going to select `date` (the observation date), `wdw_ticket_season` (the ticket season for the observation), `wdwmaxtemp` (the maximum temperature), `mkclose` (the time Magic Kingdom closed), `mkemhmorn` (whether Magic Kingdom had an \"Extra Magic Hour\" in the morning).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks_metadata_clean <- parks_metadata_raw |>\n  ##  based on our analysis plan, we will select the following variables\n  select(date, wdw_ticket_season, wdwmaxtemp, mkclose, mkemhmorn) |>\n  ## based on eligibility criteria, limit to 2018\n  filter(year(date) == 2018) |>\n  ## rename variables\n  rename(\n    park_date = date,\n    park_ticket_season = wdw_ticket_season,\n    park_temperature_high = wdwmaxtemp,\n    park_close = mkclose,\n    park_extra_magic_morning = mkemhmorn\n  )\n```\n:::\n\n\n## Working with multiple data sources\n\nFrequently we find ourselves merging data from multiple sources when attempting to answer causal questions in order to ensure that all of the necessary factors are accounted for.\nThe way we can combine datasets is via *joins* -- joining two or more datasets based on a set or sets of common variables.\nWe can think of three main types of *joins*: left, right, and inner.\nA *left* join combines data from two datasets based on a common variable and includes all records from the *left* dataset along with matching records from the *right* dataset (in `{dplyr}`, `left_join()`), while a *right* join includes all records from the *right* dataset and their corresponding matches from the *left* dataset (in `{dplyr}` `right_join()`); an inner join, on the other hand, includes only the records with matching values in *both* datasets, excluding non-matching records (in `{dplyr}` `inner_join()`.\nFor this analysis, we need to use a left join to pull in the cleaned parks metadata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseven_dwarfs_train_2018 <- seven_dwarfs_train_2018 |>\n  left_join(parks_metadata_clean, by = \"park_date\")\n```\n:::\n\n\n## Recognizing missing data\n\nIt is important to recognize whether we have any missing data in our variables.\nThe `{visdat}` package is great for getting a quick sense of whether we have any missing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(visdat)\nvis_miss(seven_dwarfs_train_2018)\n```\n\n::: {.cell-output-display}\n![](07-prep-data_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nIt looks like we only have a few observations (2%) missing our outcome of interest.\nThis is not too bad.\nFor this first analysis we will ignore the missing values.\nWe can explicitly drop them using the `drop_na()` function from `{dplyr}`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseven_dwarfs_train_2018 <- seven_dwarfs_train_2018 |>\n  drop_na()\n```\n:::\n\n\n## Exploring and visualizing data and assumptions\n\nThe *positivity* assumption requires that within each level and combination of the study variables used to achieve exchangeability, there are exposed and unexposed subjects (@sec-assump).\nWe can explore this by visualizing the distribution of each of our proposed confounders stratified by the exposure.\n\n### Single variable checks for positivity violations\n\n@fig-close shows the distribution of Magic Kingdom park closing time by whether the date had extra magic hours in the morning.\nThere is not clear evidence of a lack of positivity here as both exposure levels span the majority of the covariate space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  seven_dwarfs_train_2018,\n  aes(\n    x = factor(park_close),\n    group = factor(park_extra_magic_morning),\n    fill = factor(park_extra_magic_morning)\n  )\n) +\n  geom_bar(position = position_dodge2(width = 0.9, preserve = \"single\")) +\n  labs(\n    fill = \"Extra Magic Morning\",\n    x = \"Time of Park Close\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of Magic Kingdom park closing time by whether the date had extra magic hours in the morning](07-prep-data_files/figure-html/fig-close-1.png){#fig-close width=672}\n:::\n:::\n\n\nTo examine the distribution of historic temperature high at Magic Kingdom by whether the date had extra magic hours in the morning we can use a mirrored histogram.\nWe'll use the {halfmoon} package's `geom_mirror_histogram()` to create one.\nExamining @fig-temp, it does look like there are very few days in the exposed group with maximum temperatures less than 60 degrees, while not necessarily a positivity violation it is worth keeping an eye on, particularly because the dataset is not very large, so this could make it difficult to estimate an average exposure effect across this whole space.\nIf we found this to be particularly difficult, we could posit changing our causal question to instead restrict the analysis to warmer days.\nThis of course would also restrict which days we could draw conclusions about for the future.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(halfmoon)\nggplot(\n  seven_dwarfs_train_2018,\n  aes(\n    x = park_temperature_high,\n    group = factor(park_extra_magic_morning),\n    fill = factor(park_extra_magic_morning)\n  )\n) +\n  geom_mirror_histogram(bins = 20) +\n  labs(\n    fill = \"Extra Magic Morning\",\n    x = \"Historic maximum temperature (degrees F)\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of historic temperature high at Magic Kingdom by whether the date had extra magic hours in the morning](07-prep-data_files/figure-html/fig-temp-1.png){#fig-temp width=672}\n:::\n:::\n\n\nFinally, let's look at the distribution of ticket season by whether there were extra magic hours in the morning.\nExamining @fig-ticket, we do not see any positivity violations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  seven_dwarfs_train_2018,\n  aes(\n    x = park_ticket_season,\n    group = factor(park_extra_magic_morning),\n    fill = factor(park_extra_magic_morning)\n  )\n) +\n  geom_bar(position = \"dodge\") +\n  labs(\n    fill = \"Extra Magic Morning\",\n    x = \"Magic Kingdom Ticket Season\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of historic temperature high at Magic Kingdom by whether the date had extra magic hours in the morning](07-prep-data_files/figure-html/fig-ticket-1.png){#fig-ticket width=672}\n:::\n:::\n\n\n### Multiple variable checks for positivity violations\n\nWe have confirmed that for each of the three confounders, we do not see strong evidence of positivity violations.\nBecause we have so few variables here, we can examine this a bit more closely.\nLet's start by discretizing the `park_temperature_high` variable a bit (we will cut it into tertiles).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseven_dwarfs_train_2018 |>\n  ## cut park_temperature_high into tertiles\n  mutate(park_temperature_high_bin = cut(park_temperature_high, breaks = 3)) |>\n  ## bin park close time\n  mutate(park_close_bin = case_when(\n    hour(park_close) < 19 & hour(park_close) > 12 ~ \"(1) early\",\n    hour(park_close) >= 19 & hour(park_close) < 24 ~ \"(2) standard\",\n    hour(park_close) >= 24 | hour(park_close) < 12 ~ \"(3) late\"\n  )) |>\n  group_by(park_close_bin, park_temperature_high_bin, park_ticket_season) |>\n  ## calculate the proportion exposed in each bin\n  summarise(prop_exposed = mean(park_extra_magic_morning), .groups = \"drop\") |>\n  ggplot(aes(x = park_close_bin, y = park_temperature_high_bin, fill = prop_exposed)) +\n  geom_tile() +\n  scale_fill_gradient2(midpoint = 0.5) +\n  facet_wrap(~park_ticket_season) +\n  labs(\n    y = \"Historic Maximum Temperature (F)\",\n    x = \"Magic Kingdom Park Close Time\",\n    fill = \"Proportion of Days Exposed\"\n  )\n```\n\n::: {.cell-output-display}\n![Check for positivity violations across three confounders: historic high temperature, park close time, and ticket season.](07-prep-data_files/figure-html/fig-positivity-1.png){#fig-positivity width=864}\n:::\n:::\n\n\nInteresting!\n@fig-positivity shows an interesting potential violation.\nIt looks like 100% of days with lower temperatures (historic highs between 51 and 65 degrees) that are in the peak ticket season have extra magic hours in the morning.\nThis actually makes sense if we think a bit about this data set.\nThe only days with cold temperatures in Florida that would also be considered a \"peak\" time to visit Walt Disney World would be over Christmas / New Years.\nDuring this time there historically were always extra magic hours.\n\nWe are going to proceed with the analysis, but we will keep these observations in mind.\n\n## Presenting descriptive statistics\n\nLet's examine a table of the variables of interest in this data frame.\nTo do so, we are going to use the `tbl_summary()` function from the `{gtsummary}` package.\n(We'll also use the `{labelled}` package to clean up the variable names for the table.)\n\n\n::: {#tbl-unweighted-gtsummary .cell tbl-cap='A descriptive table of Extra Magic Morning in the touringplans dataset. This table shows the distributions of these variables in the observed population.'}\n\n```{.r .cell-code}\nlibrary(gtsummary)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#BlackLivesMatter\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(labelled)\nseven_dwarfs_train_2018 <- seven_dwarfs_train_2018 |>\n  set_variable_labels(\n    park_ticket_season = \"Ticket Season\",\n    park_close = \"Close Time\",\n    park_temperature_high = \"Historic High Temperature\"\n  )\n\ntbl_summary(\n  seven_dwarfs_train_2018,\n  by = park_extra_magic_morning,\n  include = c(park_ticket_season, park_close, park_temperature_high)\n) |>\n  # add an overall column to the table\n  add_overall(last = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"axyewyxsen\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#axyewyxsen table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#axyewyxsen thead, #axyewyxsen tbody, #axyewyxsen tfoot, #axyewyxsen tr, #axyewyxsen td, #axyewyxsen th {\n  border-style: none;\n}\n\n#axyewyxsen p {\n  margin: 0;\n  padding: 0;\n}\n\n#axyewyxsen .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#axyewyxsen .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#axyewyxsen .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#axyewyxsen .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#axyewyxsen .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#axyewyxsen .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#axyewyxsen .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#axyewyxsen .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#axyewyxsen .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#axyewyxsen .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#axyewyxsen .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#axyewyxsen .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#axyewyxsen .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#axyewyxsen .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#axyewyxsen .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#axyewyxsen .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#axyewyxsen .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#axyewyxsen .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#axyewyxsen .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#axyewyxsen .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#axyewyxsen .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#axyewyxsen .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#axyewyxsen .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#axyewyxsen .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#axyewyxsen .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#axyewyxsen .gt_left {\n  text-align: left;\n}\n\n#axyewyxsen .gt_center {\n  text-align: center;\n}\n\n#axyewyxsen .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#axyewyxsen .gt_font_normal {\n  font-weight: normal;\n}\n\n#axyewyxsen .gt_font_bold {\n  font-weight: bold;\n}\n\n#axyewyxsen .gt_font_italic {\n  font-style: italic;\n}\n\n#axyewyxsen .gt_super {\n  font-size: 65%;\n}\n\n#axyewyxsen .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#axyewyxsen .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#axyewyxsen .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#axyewyxsen .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#axyewyxsen .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#axyewyxsen .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#axyewyxsen .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;0&lt;/strong&gt;, N = 294&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>0</strong>, N = 294<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;1&lt;/strong&gt;, N = 60&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>1</strong>, N = 60<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Overall&lt;/strong&gt;, N = 354&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Overall</strong>, N = 354<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ticket Season</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    peak</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">60 (20%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">78 (22%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    regular</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">158 (54%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">35 (58%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">193 (55%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    value</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">76 (26%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">7 (12%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">83 (23%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Close Time</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16:30:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (0.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">37 (13%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">55 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">18 (6.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2 (3.3%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">20 (5.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">28 (9.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">28 (7.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">91 (31%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">102 (29%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">78 (27%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">89 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">40 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17 (28%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">57 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (1.7%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2 (0.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Historic High Temperature</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">84 (78, 89)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">83 (76, 87)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">84 (78, 89)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n",
    "supporting": [
      "07-prep-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}