# Missingness {#sec-missingness}

{{< include 00-setup.qmd >}}

Missing data is a problem for most real datasets that impacts all three types of analysis: description, prediction, and causal inference. As with analysis, the impact of missingness is also different across all three, even when we are using the same tools (like multiple imputation) to address it. You can think of missingness as an extreme version of measurement error: we intended to measure certain variables that are important for the analysis and in some capacity have not succeeded. In this chapter, we'll explore how bias can arise in causal analyses in the presence of missingness and how to address them (if we can!).

## Missingness and measurement error as structural bias

Thus far, we've made a big assumption in our DAGs that the variables that we've included are actually the variables we have in our data. In other words, we assume that the data is measured perfectly. This is almost always untrue. Let's consider a few scenarios using causal diagrams to understand the impact of mismeasurement and missingness.

Both measurement error and missingness are often visualized in DAGs as either an *indicator* of missingness, something akin to second variable on which you're conditioning, and a second variable that represents the variable as you have it measured. We'll use the second approach: Each variable we'll have a second node that represents the variable-as-observed. Let's look at an example.

In the Touring Plans data, most variables are complete and likely measured with high accuracy (e.g., ticket season and historic weather are well-measured). One variable with missingness and measurement error is the actual wait times for rides. If you recall, the data relies on humans to wait in line, either consumers of the data who report their experience or people hired to wait in line to report the wait time. Thus, missingness is largely related to whether or not someone is there there to measure the wait time. When someone is there to measure it, it's also likely measured with error, e.g. someone estimating their wait time and submitting it to Touring Plans is likely producing a value with more error than someone paid to stay in line and count the minutes. Both aspects can be captured by treating the measured value as a separate node. 

That said, let's take measurement error and missingness one at a time. First, let's consider measurement error. In @fig-meas-err-dag, the measured versions of actual and posted wait times have two variables that influence them: the real values and unknown or unmeasured factors that influence their mismeasurement. Notably, the ways in which the two wait times are mismeasured are independent of one another. 

The posted wait times are scraped by Touring Plans from what Disney posts on the web. There is a plausible mechanism by which which this could be mismeasured: Disney could post the wrong times online compared to what's posted at the park, or Touring Plans could have a mistake in its data acquisition code. That said, it's reasonable to assume that this would probably be small.

Actual wait times, on the other hand, probably have a good deal of measurement error. Humans have to manually measure this period, so there is some natural error there, and as stated above, the person measuring it may or may not be incentivized to be accurate. 

```{r}
#| label: fig-meas-err-dag
#| echo: false
labels <- c(
  "actual" = "actual wait",
  "actual_star" = "measured actual",
  "posted" = "posted wait",
  "posted_star" = "measured posted",
  "u_posted" = "unknown",
  "u_actual" = "unknown "
)

dagify(
  actual ~ posted,
  posted_star ~ u_posted + posted,
  actual_star ~ u_actual + actual,
  coords = time_ordered_coords(),
  labels = labels
) |> 
  tidy_dagitty() |> 
  mutate(label = stringr::str_trim(label)) |> 
  ggdag(use_text = FALSE, use_labels = TRUE)
```

In @fig-meas-err-dag, we're assuming that the measurement of actual wait time has no impact on posted wait time and vice versa. Because posted time happens before actual time, it's reasonable to assume that that is the case for that relationship. However, the posted wait time *may* influence the missingness of 

## Multiple Imputation

## Combining MICE and IPW
