# What is a causal question?

How do we use data to understand the world around us?
We can think of three main goals, each with different tools to accomplish them:

1.  Description
2.  Prediction
3.  Explanation

**Description** involves observing data and describing what is seen.
Descriptive studies are general not experimental, in other words nothing is manipulated, phenomena are simply observed as they are.
With the rise of "big data" simply describing what the data demonstrate is a monumental task, and often extremely valuable.
This often involves describing *what* phenomena occur or occurred in the past.

**Prediction** involves using data to forecast what will be.
With the rise of machine learning and advanced computing power prediction has become more widely accessible.
While the underlying mechanism may be well understood, it is not strictly necessary.
This often involves predicting *whether* a certain phenomena will occur given a set of circumstances.

**Explanation** involves understand *why* a phenomena occurs.
This is where causal inference shines, and where the bulk of this text will focus.
While some aspects of these goals are distinct, there is certainly overlap between them.

## Answering causal questions: assumptions

The most straight forward way to answer a causal question is to run a controlled experiment.
Such an experiment would be designed to manipulate the causal factor in question.
For example, if we are interested in assessing whether having a green background on a website increases sales of a particular item compared to a grey background, we could randomly show some people a green background and some people a grey background and compare the average sales between them.
Even this small, controlled, experiment that we just described comes with some assumptions.
Since we have *randomly* assigned people to either see the green background or the grey background, we assume that we can make a direct comparison of their average outcome (sales).

### Target trials

## The whole game
