# Preface {.unnumbered}

Welcome!
In this book, we will...

Part 1: Asking Causal Questions

* Chapter 1: What is a causal question?  
  - Description, prediction, and explanation  
  - Causal assumptions  
  - Whole game example  
  
* Chapter 2: Expressing causal questions as DAGs  
  - Visualizing causal assumptions  
  - DAGs in R: ggdag and dagitty  

* Chapter 3: Estimating counterfactuals  
  - What is a counterfactual?  
  - Target trials  
    - Time zero (only pre-treatment covariates etc)

Part 2: Design Phase

* Chapter 4: Preparing data to answer causal questions  
  - Data wrangling with dplyr  
  - Recognizing missing data: visdat, tidyr, mice  
  - Working with multiple data sources  
  - Exploring and visualizing data and assumptions: skimr, ggplot2  
  - Calculating summary statistics: gtsummary, tableone  
  
* Chapter 5: Building a propensity score models  
  - Logistic regression  
  - Choosing variables to include  
  - Continuous and categorical exposures  
  
* Chapter 6: Using the propensity score  
  - Matching  
  - Weighting  
  - Weighting and matching with more complex exposures  
  
* Chapter 7: Evaluating your propensity score model  
  - Calculating the standardized mean difference  
  - Weighted / Matched Table 1
    - ATE (match Overall column of unweighted Table 1)
    - ATT (match treatment column of unweighted Table 1)
    - ATC (match control column of unweighted Table 1) 
    - ATM / ATO
  - Visualizing balance via Love Plots, boxplots, and eCDF plots  
  - Pruning, trimming, and stabilizing propensity scores  
 
Part 3. Estimating causal effects

* Chapter 8: Causal Estimands
  - Estimating the average treatment effect  
  - Estimating treatment effects with other targets in mind  

* Chapter 9: Incorporating propensity scores in generalized linear models  
  - Using matched data sets  
  - Using weights in outcome models  
  - Estimating uncertainty  
  - Estimating causal effects for complex exposures  
  
* Chapter 10: Incorporating propensity scores in survival models
  - Time Zero  
  - Preparing data for survival analysis  
  - Pooled logistic regression  
  - Confidence intervals for causal survival models  

* Chapter 11: Mediation analyses
  - Estimating direct effects
  - Estimating indirect effects
  - Allowing for interactions

* Chapter 12: Sensitivity analyses  
  - Quantitative bias analyses  
  - Tipping point analyses: tipr, E-Value
  
* Chapter 13: Other approaches to causal inference  
  - G-computation  
  - Targeted Learning  
  - Instrumental variable analysis  
  - Regression discontinuity  
  - Difference-in-Difference
