{
  "hash": "057101694c7f228678755b6bfd2ac9ae",
  "result": {
    "markdown": "# Causal estimands {#sec-estimands}\n\n\n\n\n\n## Estimands, Estimators, Estimates\n\nWhen analyzing to make causal inferences, we need to keep the causal question that we're interested in close to our chest.\nThe causal question helps guide not just the assumptions we need to make but also how we will go about answering the question.\nThis chapter deals with three ideas closely related to answering causal questions: the estimand, the estimator, and the estimate.\nThe **estimand** is the *target of interest*, the **estimator** is the method by which we approximate this estimand using data, and the **estimate** is the value we get when we plug our data into the estimator.\nYou can think of the **estimand** as a glossy picture of a beautiful cake we are trying to bake, the **estimator** as the recipe, and the **estimate** as the cake we pull out of our oven.\n\nSo far, we have been estimating the average treatment effect, the effect of the exposure of interest averaged across the whole population.\nThe **estimand** here is the expected value of the difference in potential outcomes across all individuals:\n\n$$E[Y(1) - Y(0)]$$\n\nThe **estimator** we use depends on the method we've chosen.\nFor example, in an A/B test or randomized controlled trial, our estimator could just be the average outcome among those who received the exposure A minus the average outcome among those who receive exposure B.\n\n$$\\sum_{i=1}^{N}\\frac{Y_i\\times X_i}{N_{\\textrm{A}}} - \\frac{Y_i\\times (1-X_i)}{N_{\\textrm{B}}}$$\n\nWhere $X$ is just an indicator for exposure A ($X = 1$ for exposure A and $X = 0$ for exposure B), $N_A$ is the total number in group A and $N_B$ is the total number in group B such that $N_A + N_B = N$.\nLet's motivate this example a bit more.\nSuppose we have two different designs for a call-to-action (often abbreviated as CTA, a written directive for a marketing campaign) and want to assess whether they lead to a different average number of items a user purchases.\nWe can create an A/B test where we randomly assign a subset of users to see design A or design B.\nSuppose we have A/B testing data for 100 participants in a dataset called `ab`.\nHere is some code to simulate such a data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(928)\nab <- tibble(\n  # generate the exposure, x, from a binomial distribution\n  # with the probability exposure A of 0.5\n  x = rbinom(100, 1, 0.5),\n  # generate the \"true\" average treatment effect of 1\n  # we use rnorm(100) to add the random error term that is normally\n  # distributed with a mean of 0 and a standard deviation of 1\n  y = x + rnorm(100)\n)\n```\n:::\n\n\nHere the exposure is `x`, and the outcome is `y`.\nThe true average treatment effect is 1, implying that on average seeing call-to-action A increases the number of items purchased by 1.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 2\n       x      y\n   <int>  <dbl>\n 1     0 -0.280\n 2     1  1.87 \n 3     1  1.36 \n 4     0 -0.208\n 5     0  1.13 \n 6     1  0.352\n 7     1 -0.148\n 8     1  2.08 \n 9     0  2.09 \n10     0 -1.41 \n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\nBelow are two ways to estimate this in R.\nUsing a formula approach, we calculate the difference in `y` between exposure values in the first example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab |>\n  summarise(\n    n_a = sum(x),\n    n_b = sum(1 - x),\n    estimate = sum(\n      (y * x) / n_a -\n        y * (1 - x) / n_b\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n    n_a   n_b estimate\n  <int> <dbl>    <dbl>\n1    54    46     1.15\n```\n\n\n:::\n:::\n\n\nAlternatively, we can `group_by()` `x` and `summarize()` the means of `y` for each group, then pivot the results to take their difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab |>\n  group_by(x) |>\n  summarise(avg_y = mean(y)) |>\n  pivot_wider(\n    names_from = x,\n    values_from = avg_y,\n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  estimate\n     <dbl>\n1     1.15\n```\n\n\n:::\n:::\n\n\nBecause $X$, the exposure, was randomly assigned, this estimator results in an unbiased estimate of our estimand of interest.\n\nWhat do we mean by unbiased, though?\nNotice that while the \"true\" causal effect is 1, this estimate is not precisely 1; it is 1.149.\nWhy the difference?\nThis A/B test included a sample of 100 participants, not the whole population.\nAs that sample increases, our estimate will get closer to the truth.\nLet's try that.\nLet's simulate the data again but increase the sample size from 100 to 100,000:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(928)\nab <- tibble(\n  x = rbinom(100000, 1, 0.5),\n  y = x + rnorm(100000)\n)\n\nab |>\n  summarise(\n    n_a = sum(x),\n    n_b = sum(1 - x),\n    estimate = sum(\n      (y * x) / n_a -\n        y * (1 - x) / n_b\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n    n_a   n_b estimate\n  <int> <dbl>    <dbl>\n1 49918 50082     1.01\n```\n\n\n:::\n:::\n\n\nNotice how the estimate is 1.01, much closer to the actual average treatment effect, 1.\n\nSuppose $X$ had not been randomly assigned.\nIn that case, we could use the pre-exposure covariates to estimate the conditional probability of $X$ (the propensity score) and incorporate this probability in a *weight* $(w_i)$ to estimate this causal effect.\nFor example, we could use the following *estimator* to *estimate* our average treatment effect *estimand*:\n\n$$\\frac{\\sum_{i=1}^NY_i\\times X_i\\times w_i}{\\sum_{i=1}^NX_i\\times w_i}-\\frac{\\sum_{i=1}^NY_i\\times(1-X_i)\\times w_i}{\\sum_{i=1}^N(1-X_i)\\times w_i}$$\n\n## Estimating treatment effects with specific targets in mind\n\nDepending on the study's goal, or the causal question, we may want to estimate different *estimands*.\nHere, we will outline the most common causal estimands, their target populations, the causal questions they may help answer, and the methods used to estimate them [@greifer2021choosing].\n\n### Average treatment effect\n\nA common estimand is the average treatment effect (ATE).\nThe target population is the *total sample* or population of interest.\nThe **estimand** here is the expected value of the difference in potential outcomes across all individuals:\n\n$$E[Y(1) - Y(0)]$$\n\nAn example research question is \"Should a policy be applied to all eligible patients?\" [@greifer2021choosing].\n\nMost randomized controlled trials are designed with the ATE as the target estimand.\nIn a non-randomized setting, you can estimate the ATE using full matching.\nEach observation in the exposed group is matched to at least one observation in the control group (and vice versa) without replacement.\nAlternatively, the following inverse probability weight will allow you to estimate the ATE using propensity score weighting.\n\n$$w_{ATE} = \\frac{X}{p} + \\frac{(1 - X)}{1 - p}$$\n\nIn other words, the weight is one over the propensity score for those in the exposure group and one over one minus the propensity score for the control group.\nIntuitively, this weight equates to the inverse probability of being in the exposure group in which you actually were.\n\nLet's dig deeper into this causal estimand using the Touring Plans data.\nRecall that in @sec-using-ps, we examined the relationship between whether there were \"Extra Magic Hours\" in the morning and the average wait time for the Seven Dwarfs Mine Train the same day between 9 am and 10 am.\nLet's reconstruct our data set, `seven_dwarfs` and fit the same propensity score model specified previously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(touringplans)\n\nseven_dwarfs <- seven_dwarfs_train_2018 |>\n  filter(wait_hour == 9) |>\n  mutate(park_extra_magic_morning = factor(\n    park_extra_magic_morning,\n    labels = c(\"No Magic Hours\", \"Extra Magic Hours\")\n  ))\n\nseven_dwarfs_with_ps <- glm(\n  park_extra_magic_morning ~ park_ticket_season + park_close + park_temperature_high,\n  data = seven_dwarfs,\n  family = binomial()\n) |>\n  augment(type.predict = \"response\", data = seven_dwarfs)\n```\n:::\n\n\nLet's examine a table of the variables of interest in this data frame.\nTo do so, we are going to use the `tbl_summary()` function from the `{gtsummary}` package.\n(We'll also use the `{labelled}` package to clean up the variable names for the table.)\n\n\n::: {#tbl-unweighted-gtsummary .cell tbl-cap='A descriptive table of Extra Magic Morning in the touringplans dataset. This table shows the distributions of these variables in the observed population.'}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nlibrary(labelled)\nseven_dwarfs_with_ps <- seven_dwarfs_with_ps |>\n  set_variable_labels(\n    park_ticket_season = \"Ticket Season\",\n    park_close = \"Close Time\",\n    park_temperature_high = \"Historic High Temperature\"\n  )\n\ntbl_summary(\n  seven_dwarfs_with_ps,\n  by = park_extra_magic_morning,\n  include = c(park_ticket_season, park_close, park_temperature_high)\n) |>\n  # add an overall column to the table\n  add_overall(last = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"eugzvcxdgr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#eugzvcxdgr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#eugzvcxdgr thead, #eugzvcxdgr tbody, #eugzvcxdgr tfoot, #eugzvcxdgr tr, #eugzvcxdgr td, #eugzvcxdgr th {\n  border-style: none;\n}\n\n#eugzvcxdgr p {\n  margin: 0;\n  padding: 0;\n}\n\n#eugzvcxdgr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#eugzvcxdgr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eugzvcxdgr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eugzvcxdgr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eugzvcxdgr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eugzvcxdgr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eugzvcxdgr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eugzvcxdgr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eugzvcxdgr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#eugzvcxdgr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#eugzvcxdgr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eugzvcxdgr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eugzvcxdgr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eugzvcxdgr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eugzvcxdgr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eugzvcxdgr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eugzvcxdgr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eugzvcxdgr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#eugzvcxdgr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eugzvcxdgr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eugzvcxdgr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eugzvcxdgr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eugzvcxdgr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eugzvcxdgr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eugzvcxdgr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eugzvcxdgr .gt_left {\n  text-align: left;\n}\n\n#eugzvcxdgr .gt_center {\n  text-align: center;\n}\n\n#eugzvcxdgr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eugzvcxdgr .gt_font_normal {\n  font-weight: normal;\n}\n\n#eugzvcxdgr .gt_font_bold {\n  font-weight: bold;\n}\n\n#eugzvcxdgr .gt_font_italic {\n  font-style: italic;\n}\n\n#eugzvcxdgr .gt_super {\n  font-size: 65%;\n}\n\n#eugzvcxdgr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#eugzvcxdgr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eugzvcxdgr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#eugzvcxdgr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#eugzvcxdgr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#eugzvcxdgr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#eugzvcxdgr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;No Magic Hours&lt;/strong&gt;, N = 294&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>No Magic Hours</strong>, N = 294<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Extra Magic Hours&lt;/strong&gt;, N = 60&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Extra Magic Hours</strong>, N = 60<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Overall&lt;/strong&gt;, N = 354&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Overall</strong>, N = 354<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ticket Season</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    peak</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">60 (20%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">78 (22%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    regular</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">158 (54%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">35 (58%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">193 (55%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    value</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">76 (26%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">7 (12%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">83 (23%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Close Time</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16:30:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (0.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">37 (13%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">55 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">18 (6.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2 (3.3%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">20 (5.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">28 (9.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">28 (7.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">91 (31%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">102 (29%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">78 (27%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">89 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">40 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17 (28%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">57 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (1.7%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2 (0.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Historic High Temperature</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">84 (78, 89)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">83 (76, 87)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">84 (78, 89)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nFrom @tbl-unweighted-gtsummary, 294 days did not have extra magic hours in the morning, and 60 did.\nWe also see that 30% of the extra magic mornings were during peak season compared to 20% of the non-extra magic mornings.\nAdditionally, days with extra magic mornings were more likely to close at 6 pm (18:00:00) compared to non-magic hour mornings.\nThe median high temperature on days with extra magic hour mornings is slightly lower (83 degrees) compared to non-extra magic hour morning days.\n\nNow let's construct our propensity score weight to estimate the ATE.\nThe `{propensity}` package has helper functions to estimate weights.\nThe `wt_ate()` function will calculate ATE weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(propensity)\nseven_dwarfs_wts <- seven_dwarfs_with_ps |>\n  mutate(w_ate = wt_ate(.fitted, park_extra_magic_morning))\n```\n:::\n\n\nLet's look at a distribution of these weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(seven_dwarfs_wts, aes(x = w_ate)) +\n  geom_histogram(bins = 50)\n```\n\n::: {.cell-output-display}\n![A histogram of the average treatment effect (ATE) weights for whether or not a day had extra magic hours. ATE weights can range from 1 to infinity, so paying attention to the actual range of weights is important.](11-estimands_files/figure-html/fig-sd-ate-hist-1.png){#fig-sd-ate-hist width=672}\n:::\n:::\n\n\nMany weights in @fig-sd-ate-hist are close to 1 (the smallest possible value for an ATE weight), with a long tail leading to the largest weight (around 24).\nThis distribution highlights a potential problem with ATE weights.\nThey range from 1 to infinity; if your weights are too large in small samples, this can lead to bias in your estimates (known as finite sample bias).\n\n::: {.callout-warning}\n## Finite sample bias\n\nWe know that not accounting for confounders can bias our causal estimates, but it turns out that even after accounting for all confounders, we may still get a biased estimate in finite samples.\nMany of the properties we tout in statistics rely on *large samples*---how \"large\" is defined can be opaque.\nLet's look at a quick simulation.\nHere, we have an exposure, $X$, an outcome, $Y$, and one confounder, $Z$.\nWe will simulate $Y$, which is only dependent on $Z$ (so the true treatment effect is 0), and $X$, which also depends on $Z$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(928)\nn <- 100\nfinite_sample <- tibble(\n  # z is normally distributed with a mean: 0 and sd: 1\n  z = rnorm(n),\n  # x is defined from a probit selection model with normally distributed errors\n  x = case_when(\n    0.5 + z + rnorm(n) > 0 ~ 1,\n    TRUE ~ 0\n  ),\n  # y is continuous, dependent only on z with normally distrbuted errors\n  y = z + rnorm(n)\n)\n```\n:::\n\n\nIf we fit a propensity score model using the one confounder $Z$ and calculate the weighted estimator, we should get an unbiased result (which in this case would be 0).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fit the propensity score model\nfinite_sample_wts <- glm(\n  x ~ z,\n  data = finite_sample,\n  family = binomial(\"probit\")\n) |>\n  augment(newdata = finite_sample, type.predict = \"response\") |>\n  mutate(wts = wt_ate(.fitted, x))\n\nfinite_sample_wts |>\n  summarize(\n    effect = sum(y * x * wts) / sum(x * wts) -\n      sum(y * (1 - x) * wts) / sum((1 - x) * wts)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  effect\n   <dbl>\n1  0.197\n```\n\n\n:::\n:::\n\n\nOk, here, our effect of $X$ is pretty far from 0, although it's hard to know if this is really bias, or something we are just seeing by chance in this particular simulated sample.\nTo explore the potential for finite sample bias, we can rerun this simulation many times at different sample sizes.\nLet's do that.\n\n\n::: {.cell hash='11-estimands_cache/html/sim-finite-sample-bias_fc62762d9112d2aa58d8f14393ce0072'}\n\n```{.r .cell-code}\nsim <- function(n) {\n  ## create a simulated dataset\n  finite_sample <- tibble(\n    z = rnorm(n),\n    x = case_when(\n      0.5 + z + rnorm(n) > 0 ~ 1,\n      TRUE ~ 0\n    ),\n    y = z + rnorm(n)\n  )\n  finite_sample_wts <- glm(\n    x ~ z,\n    data = finite_sample,\n    family = binomial(\"probit\")\n  ) |>\n    augment(newdata = finite_sample, type.predict = \"response\") |>\n    mutate(wts = wt_ate(.fitted, x))\n  bias <- finite_sample_wts |>\n    summarize(\n      effect = sum(y * x * wts) / sum(x * wts) -\n        sum(y * (1 - x) * wts) / sum((1 - x) * wts)\n    ) |>\n    pull()\n  tibble(\n    n = n,\n    bias = bias\n  )\n}\n\n## Examine 5 different sample sizes, simulate each 1000 times\nset.seed(1)\nfinite_sample_sims <- map_df(\n  rep(\n    c(50, 100, 500, 1000, 5000, 10000),\n    each = 1000\n  ),\n  sim\n)\n\nbias <- finite_sample_sims %>%\n  group_by(n) %>%\n  summarise(bias = mean(bias))\n```\n:::\n\n\nLet's plot our results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bias, aes(x = n, y = bias)) +\n  geom_point() +\n  geom_line() +\n  geom_hline(yintercept = 0, lty = 2)\n```\n\n::: {.cell-output-display}\n![Finite sample bias present with ATE weights created using correctly specified propensity score model, varying the sample size from n = 50 to n = 10,000](11-estimands_files/figure-html/fig-finite-sample-bias-1.png){#fig-finite-sample-bias width=672}\n:::\n:::\n\n\nThis is an example of finite sample bias.\nNotice here, even when the sample size is quite large (5,000) we still see some bias away from the \"true\" effect of 0.\nIt isn't until a sample size larger than 10,000 that we see this bias disappear.\n\nEstimands that utilize weights that are unbounded (i.e. that theoretically can be infinitely large) are more likely to suffer from finite sample bias.\nThe likelihood of falling into finite sample bias depends on:\\\n(1) the estimand you have chosen (i.e. are the weights bounded?)\\\n(2) the distribution of the covariates in the exposed and unexposed groups (i.e. is there good overlap? Potential positivity violations, when there is poor overlap, are the regions where weights can become too large)\\\n(3) the sample size.\n:::\n\nThe `{gtsummary}` package allows the creation of *weighted* tables, which can help us build an intuition for the psuedopopulation created by the weights.\nFirst, we must load the `{survey}` package and create a survey design object.\nThe `{survey}` package supports calculating statistics and models using weights.\nHistorically, many researchers applied techniques incorporating weights to survey analyses.\nEven though we are not doing a survey analysis, the same techniques are helpful for our propensity score weights.\n\n\n::: {#tbl-weighted-gtsummary .cell tbl-cap='A descriptive table of Extra Magic Morning hours weighted by the Average Treatment Effect Weights. This table shows the distributions of these variables in the psuedopopulation created by these weights.'}\n\n```{.r .cell-code}\nlibrary(survey)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'Matrix' was built under R version\n4.2.3\n```\n\n\n:::\n\n```{.r .cell-code}\nseven_dwarfs_svy <- svydesign(\n  ids = ~1,\n  data = seven_dwarfs_wts,\n  weights = ~w_ate\n)\ntbl_svysummary(\n  seven_dwarfs_svy,\n  by = park_extra_magic_morning,\n  include = c(park_ticket_season, park_close, park_temperature_high)\n) |>\n  add_overall(last = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uaaskkmbew\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uaaskkmbew table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uaaskkmbew thead, #uaaskkmbew tbody, #uaaskkmbew tfoot, #uaaskkmbew tr, #uaaskkmbew td, #uaaskkmbew th {\n  border-style: none;\n}\n\n#uaaskkmbew p {\n  margin: 0;\n  padding: 0;\n}\n\n#uaaskkmbew .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uaaskkmbew .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uaaskkmbew .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uaaskkmbew .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uaaskkmbew .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uaaskkmbew .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uaaskkmbew .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uaaskkmbew .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uaaskkmbew .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uaaskkmbew .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uaaskkmbew .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uaaskkmbew .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uaaskkmbew .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uaaskkmbew .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uaaskkmbew .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uaaskkmbew .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uaaskkmbew .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uaaskkmbew .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uaaskkmbew .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uaaskkmbew .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uaaskkmbew .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uaaskkmbew .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uaaskkmbew .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uaaskkmbew .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uaaskkmbew .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uaaskkmbew .gt_left {\n  text-align: left;\n}\n\n#uaaskkmbew .gt_center {\n  text-align: center;\n}\n\n#uaaskkmbew .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uaaskkmbew .gt_font_normal {\n  font-weight: normal;\n}\n\n#uaaskkmbew .gt_font_bold {\n  font-weight: bold;\n}\n\n#uaaskkmbew .gt_font_italic {\n  font-style: italic;\n}\n\n#uaaskkmbew .gt_super {\n  font-size: 65%;\n}\n\n#uaaskkmbew .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uaaskkmbew .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uaaskkmbew .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uaaskkmbew .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uaaskkmbew .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uaaskkmbew .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uaaskkmbew .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;No Magic Hours&lt;/strong&gt;, N = 354&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>No Magic Hours</strong>, N = 354<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Extra Magic Hours&lt;/strong&gt;, N = 357&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Extra Magic Hours</strong>, N = 357<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Overall&lt;/strong&gt;, N = 711&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Overall</strong>, N = 711<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ticket Season</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    peak</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">78 (22%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">81 (23%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">160 (22%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    regular</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">193 (54%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">187 (52%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">380 (53%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    value</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">83 (23%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">89 (25%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">172 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Close Time</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16:30:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2 (0.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2 (0.2%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">50 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">72 (20%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">122 (17%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">20 (5.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">19 (5.3%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">39 (5.5%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">31 (8.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">31 (4.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">108 (30%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">86 (24%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">193 (27%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">95 (27%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">81 (23%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">176 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">48 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (26%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">142 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6 (1.6%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">7 (1.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Historic High Temperature</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">84 (78, 89)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">83 (78, 87)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">84 (78, 88)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nNotice in @tbl-weighted-gtsummary that the variables are more **balanced** between the groups.\nFor example, looking at the variable `park_ticket_season`, in @tbl-unweighted-gtsummary we see that a higher percentage of the days with extra magic hours in the mornings were during the peak season (30%) compared to the percent of days without extra magic hours in the morning (23%).\nIn @tbl-weighted-gtsummary this is balanced, with a weighted percent of 22% peak days in the extra magic morning group and 22% in the no extra magic morning group.\nThe weights change the variables' distribution by weighting each observation so that the two groups appear balanced.\nAlso, notice that the distribution of variables in @tbl-weighted-gtsummary now matches the Overall column of @tbl-unweighted-gtsummary.\nThat is what ATE weights do: they make the distribution of variables included in the propensity score for each exposure group look like the overall distribution across the whole sample.\n\nLet's look at another visualization that can help us understand the weighted psuedopopulation created by the ATE weights: a mirrored histogram.\nWe will plot the distribution of the propensity score for the days in the exposure group (days with extra magic hours in the morning) on the top half of the plot; then, we will mirror the distribution of the propensity score for the days in the\"unexposed group below it. This visualization allows us to compare the two distributions quickly. Then we will overlay weighted histograms to demonstrate how these distributions differ after incorporating the weights. The {halfmoon} package includes a function `geom_mirror_histogram()` to assist with this visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(halfmoon)\nggplot(seven_dwarfs_wts, aes(.fitted, group = park_extra_magic_morning)) +\n  geom_mirror_histogram(bins = 50) +\n  geom_mirror_histogram(\n    aes(fill = park_extra_magic_morning, weight = w_ate),\n    bins = 50,\n    alpha = 0.5\n  ) +\n  scale_y_continuous(labels = abs) +\n  labs(\n    x = \"propensity score\",\n    fill = \"Extra Magic Morning\"\n  )\n```\n\n::: {.cell-output-display}\n![A mirrored histogram of the distribution of propensity scores between exposure groups. The dark bars represent the unweighted distribution, and the colored bars represent the distribution weighted by the average treatment effect (ATE) weight.](11-estimands_files/figure-html/fig-sd-mirror-hist-ate-1.png){#fig-sd-mirror-hist-ate width=672}\n:::\n:::\n\n\nWe can learn a few things from @fig-sd-mirror-hist-ate.\nFirst, we can see that there are more \"unexposed\" days---days without extra magic hours in the morning---compared to \"exposed\" in the observed population.\nWe can see this by examining the darker histograms, which show the distributions in the observed sample.\nSimilarly, the exposed days are upweighted more substantially, as evidenced by the light blue we see on the top.\nWe can also see that after weighting, the two distributions look similar; the shape of the blue weighted distribution on top looks comparable to the orange weighted distribution below.\n\n### Average treatment effect among the treated\n\nThe target population to estimate the average treatment effect among the treated (ATT) is the *exposed* (treated) population.\nThis causal estimand conditions on those in the exposed group:\n\n$$E[Y(1) - Y(0) | X = 1]$$\n\nExample research questions where the ATT is of interest could include \"Should we stop our marketing campaign to those currently receiving it?\" or \"Should medical providers stop recommending treatment for those currently receiving it?\" [@greifer2021choosing]\n\nThe ATT is a common target estimand when using matching; here, all exposed observations are included and \"matched\" to control observations, some of which may be discarded.\nAlternatively, the ATT can be estimated via weighting.\nThe ATT weight is estimated by:\n\n$$w_{ATT} = X + \\frac{(1 - X)p}{1 - p}$$\n\nLet's add the ATT weights to the `seven_dwarfs_wts` data frame and look at their distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseven_dwarfs_wts <- seven_dwarfs_wts |>\n  mutate(w_att = wt_att(.fitted, park_extra_magic_morning))\n\nggplot(seven_dwarfs_wts, aes(w_att)) +\n  geom_histogram(bins = 50)\n```\n\n::: {.cell-output-display}\n![A histogram of the average treatment effect among the treated (ATT) weights. The range of the ATT weights in this example is more stable than the ATE weights: the range is much smaller.](11-estimands_files/figure-html/fig-sd-att-hist-1.png){#fig-sd-att-hist width=672}\n:::\n:::\n\n\nCompared to the ATE weights, the weights in @fig-sd-att-hist look more *stable*; the distribution of the weights is not heavily skewed, and the range is small, from ground zero to a bit over one, with many at precisely one.\nThese weights are exactly one for all days in the exposed group.\nTheoretically, for unexposed days these weights can range from zero to infinity.\nStill, because we have many more unexposed days compared to exposed in this particular sample, the range is much smaller, meaning the vast majority of unexposed days are \"down-weighted\" to match the variable distribution of the exposed days.\nLet's take a look at the weighted table to see this a bit more clearly.\n\n\n::: {#tbl-weighted-att .cell tbl-cap='A descriptive table of Extra Magic Morning hours weighted by the Average Treatment Effect among the Treated Weights. This table shows the distributions of these variables in the psuedopopulation created by these weights.'}\n\n```{.r .cell-code}\nseven_dwarfs_svy <- svydesign(\n  ids = ~1,\n  data = seven_dwarfs_wts,\n  weights = ~w_att\n)\ntbl_svysummary(\n  seven_dwarfs_svy,\n  by = park_extra_magic_morning,\n  include = c(park_ticket_season, park_close, park_temperature_high)\n) |>\n  add_overall(last = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There were 5 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `df_stats = pmap(...)`.\nCaused by warning in `svymean.survey.design2()`:\n! Sample size greater than population size: are weights correctly scaled?\nℹ Run `dplyr::last_dplyr_warnings()` to see the 4\n  remaining warnings.\nThere were 5 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `df_stats = pmap(...)`.\nCaused by warning in `svymean.survey.design2()`:\n! Sample size greater than population size: are weights correctly scaled?\nℹ Run `dplyr::last_dplyr_warnings()` to see the 4\n  remaining warnings.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nhvedgwgja\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nhvedgwgja table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nhvedgwgja thead, #nhvedgwgja tbody, #nhvedgwgja tfoot, #nhvedgwgja tr, #nhvedgwgja td, #nhvedgwgja th {\n  border-style: none;\n}\n\n#nhvedgwgja p {\n  margin: 0;\n  padding: 0;\n}\n\n#nhvedgwgja .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nhvedgwgja .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nhvedgwgja .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nhvedgwgja .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nhvedgwgja .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nhvedgwgja .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nhvedgwgja .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nhvedgwgja .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nhvedgwgja .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nhvedgwgja .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nhvedgwgja .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nhvedgwgja .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nhvedgwgja .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nhvedgwgja .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nhvedgwgja .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nhvedgwgja .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nhvedgwgja .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nhvedgwgja .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nhvedgwgja .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nhvedgwgja .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nhvedgwgja .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nhvedgwgja .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nhvedgwgja .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nhvedgwgja .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nhvedgwgja .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nhvedgwgja .gt_left {\n  text-align: left;\n}\n\n#nhvedgwgja .gt_center {\n  text-align: center;\n}\n\n#nhvedgwgja .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nhvedgwgja .gt_font_normal {\n  font-weight: normal;\n}\n\n#nhvedgwgja .gt_font_bold {\n  font-weight: bold;\n}\n\n#nhvedgwgja .gt_font_italic {\n  font-style: italic;\n}\n\n#nhvedgwgja .gt_super {\n  font-size: 65%;\n}\n\n#nhvedgwgja .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nhvedgwgja .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nhvedgwgja .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nhvedgwgja .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nhvedgwgja .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nhvedgwgja .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nhvedgwgja .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;No Magic Hours&lt;/strong&gt;, N = 60&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>No Magic Hours</strong>, N = 60<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Extra Magic Hours&lt;/strong&gt;, N = 60&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Extra Magic Hours</strong>, N = 60<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Overall&lt;/strong&gt;, N = 120&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Overall</strong>, N = 120<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ticket Season</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    peak</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">36 (30%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    regular</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">35 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">35 (58%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">70 (58%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    value</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">7 (12%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">7 (12%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">14 (12%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Close Time</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16:30:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (0.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">13 (21%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">31 (26%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2 (3.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2 (3.3%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4 (3.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3 (4.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3 (2.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">17 (28%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">28 (23%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">17 (28%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (18%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">28 (23%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17 (28%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">25 (21%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25:00:00</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (1.7%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (1.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Historic High Temperature</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">83 (74, 88)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">83 (75, 87)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">83 (75, 88)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe again achieve a balance between groups, but the target values in @tbl-weighted-att differ from the previous tables.\nRecall in our ATE weighted table (@tbl-weighted-gtsummary), when looking at the `wdw_ticket_season` variable, we saw the weighted percent in the peak season balanced close to 22%, the overall percent of peak days in the observed sample.\nWe again see balance, but the weighted percent of peak season days is 30% in the exposed and unexposed groups, reflecting the percent in the unweighted exposure group.\nIf you compare @tbl-weighted-att to our unweighted table (@tbl-unweighted-gtsummary), you might notice that the columns are most similar to the exposed column from the unweighted table.\nThis is because the \"target\" population is the exposed group, the days with extra magic hours in the morning, so we're trying to make the comparison group (no magic hours) as similar to that group as possible.\n\nWe can again create a mirrored histogram to observe the weighted psuedopopulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(seven_dwarfs_wts, aes(.fitted, group = park_extra_magic_morning)) +\n  geom_mirror_histogram(bins = 50) +\n  geom_mirror_histogram(\n    aes(fill = park_extra_magic_morning, weight = w_att),\n    bins = 50,\n    alpha = 0.5\n  ) +\n  scale_y_continuous(labels = abs) +\n  labs(\n    x = \"propensity score\",\n    fill = \"Extra Magic Morning\"\n  )\n```\n\n::: {.cell-output-display}\n![A mirrored histogram of the distribution of propensity scores between exposure groups. The dark bars represent the unweighted distribution, and the colored bars represent the distribution weighted by the average treatment effect among the treated (ATT) weight.](11-estimands_files/figure-html/fig-sd-mirror-hist-att-1.png){#fig-sd-mirror-hist-att width=672}\n:::\n:::\n\n\nSince every day in the exposed group has a weight of 1, the distribution of the propensity scores (the dark bars above 0 on the graph) in @fig-sd-mirror-hist-att overlaps exactly with the weighted distribution overlaid in blue.\nIn the unexposed population, we see that almost all observations are *down weighted*; the dark orange distribution is smaller than the distribution of the propensity scores and more closely matches the exposed distribution above it.\nThe ATT is easier to estimate when there are many more observations in the unexposed group compared to the exposed one.\n\n### Average treatment effect among the unexposed\n\nThe target population to estimate the average treatment effect among the unexposed (control) (ATU / ATC) is the *unexposed* (control) population.\nThis causal estimand conditions on those in the unexposed group.\n\n$$E[Y(1) - Y(0) | X = 0]$$\n\nExample research questions where the ATU is of interest could include \"Should we send our marketing campaign to those not currently receiving it?\" or \"Should medical providers begin recommending treatment for those not currently receiving it?\" [@greifer2021choosing]\n\nThe ATU can be estimated via matching; here, all unexposed observations are included and \"matched\" to exposed observations, some of which may be discarded.\nAlternatively, the ATU can be estimated via weighting.\nThe ATU weight is estimated by:\n\n$$w_{ATU} = \\frac{X(1-p)}{p}+ (1-X)$$ Let's add the ATU weights to the `seven_dwarfs_wts` data frame and look at their distribution.\n\nWhen fitting an outcome model on matched data sets, we can simply subset the original data to only those who were matched and then fit a model on these data as we would otherwise. For example, re-performing the matching as we did in @sec-using-ps, we can extract the matched observations in a dataset called `matched_data` as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(touringplans)\nlibrary(MatchIt)\n\nseven_dwarfs_9 <- seven_dwarfs_train_2018 |>\n  filter(wait_hour == 9)\n\nm <- matchit(\n  park_extra_magic_morning ~ park_ticket_season + park_close + park_temperature_high,\n  data = seven_dwarfs_9\n)\nmatched_data <- get_matches(m)\n```\n:::\n\n\nWe can then fit the outcome model on this data. For this analysis, we are interested in the impact of extra magic morning hours on the average posted wait time between 9 and 10am. The linear model below will estimate this in the matched cohort.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(wait_minutes_posted_avg ~ park_extra_magic_morning, data = matched_data) |>\n  tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term   estimate std.error statistic  p.value conf.low\n  <chr>     <dbl>     <dbl>     <dbl>    <dbl>    <dbl>\n1 (Inte…    67.0       2.37     28.3  1.94e-54    62.3 \n2 park_…     7.87      3.35      2.35 2.04e- 2     1.24\n# ℹ 1 more variable: conf.high <dbl>\n```\n\n\n:::\n:::\n\n\nRecall that by default `{MatchIt}` estimates an average treatment effect among the treated. This means among days that have extra magic hours, the expected impact of having extra magic hours on the average posted wait time between 9 and 10am is 7.9 minutes (95% CI: 1.2-14.5). \n\n## Using weights in outcome models\n\nNow let's use propensity score weights to estimate this same estimand. We will use the ATT weights so the analysis matches that for matching above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(propensity)\n\nseven_dwarfs_9_with_ps <-\n  glm(\n    park_extra_magic_morning ~ park_ticket_season + park_close + park_temperature_high,\n    data = seven_dwarfs_9,\n    family = binomial()\n  ) |>\n  augment(type.predict = \"response\", data = seven_dwarfs_9)\nseven_dwarfs_9_with_wt <- seven_dwarfs_9_with_ps |>\n  mutate(w_att = wt_att(.fitted, park_extra_magic_morning))\n```\n:::\n\n\nWe can fit a *weighted* outcome model by using the `weights` argument. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(\n  wait_minutes_posted_avg ~ park_extra_magic_morning,\n  data = seven_dwarfs_9_with_wt,\n  weights = w_att\n) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term           estimate std.error statistic   p.value\n  <chr>             <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)       68.7       1.45     47.3  1.69e-154\n2 park_extra_ma…     6.23      2.05      3.03 2.62e-  3\n```\n\n\n:::\n:::\n\n\nUsing weighting, we estimate that among days that have extra magic hours, the expected impact of having extra magic hours on the average posted wait time between 9 and 10am is 6.2 minutes. \nWhile this approach will get us the desired estimate for the point estimate, the default output using the `lm` function for the uncertainty (the standard errors and confidence intervals) are not correct.\n\n\n## Estimating uncertainty\n\nThere are three ways to estimate the uncertainty:\n\n1. A bootstrap\n2. A sandwich estimator that only takes into account the outcome model\n3. A sandwich estimator that takes into account the propensity score model\n\nThe first option can be computationally intensive, but should get you the correct estimates.\nThe second option is computationally the easiest, but tends to overestimate the variability. There are not many current solutions in R (aside from coding it up yourself) for the third; however, the `{PSW}` package will do this. \n\n### The bootstrap\n\n1. Create a function to run your analysis once on a sample of your data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ipw <- function(split, ...) {\n  .df <- analysis(split)\n\n  # fit propensity score model\n  propensity_model <- glm(\n    park_extra_magic_morning ~ park_ticket_season + park_close + park_temperature_high,\n    data = seven_dwarfs_9,\n    family = binomial()\n  )\n\n  # calculate inverse probability weights\n  .df <- propensity_model |>\n    augment(type.predict = \"response\", data = .df) |>\n    mutate(wts = wt_att(\n      .fitted,\n      park_extra_magic_morning,\n      exposure_type = \"binary\"\n    ))\n\n  # fit correctly bootstrapped ipw model\n  lm(\n    wait_minutes_posted_avg ~ park_extra_magic_morning,\n    data = .df,\n    weights = wts\n  ) |>\n    tidy()\n}\n```\n:::\n\n\n\n2. Use {rsample} to bootstrap our causal effect\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rsample)\n\n# fit ipw model to bootstrapped samples\nbootstrapped_seven_dwarfs <- bootstraps(\n  seven_dwarfs_9,\n  times = 1000,\n  apparent = TRUE\n)\n\nipw_results <- bootstrapped_seven_dwarfs |>\n  mutate(boot_fits = map(splits, fit_ipw))\n\nipw_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Bootstrap sampling with apparent sample \n# A tibble: 1,001 × 3\n   splits            id            boot_fits       \n   <list>            <chr>         <list>          \n 1 <split [354/146]> Bootstrap0001 <tibble [2 × 5]>\n 2 <split [354/137]> Bootstrap0002 <tibble [2 × 5]>\n 3 <split [354/123]> Bootstrap0003 <tibble [2 × 5]>\n 4 <split [354/132]> Bootstrap0004 <tibble [2 × 5]>\n 5 <split [354/135]> Bootstrap0005 <tibble [2 × 5]>\n 6 <split [354/133]> Bootstrap0006 <tibble [2 × 5]>\n 7 <split [354/127]> Bootstrap0007 <tibble [2 × 5]>\n 8 <split [354/129]> Bootstrap0008 <tibble [2 × 5]>\n 9 <split [354/132]> Bootstrap0009 <tibble [2 × 5]>\n10 <split [354/128]> Bootstrap0010 <tibble [2 × 5]>\n# ℹ 991 more rows\n```\n\n\n:::\n:::\n\n\n\nLet's look at the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nipw_results |>\n  mutate(\n    estimate = map_dbl(\n      boot_fits,\n      \\(.fit) .fit |>\n        filter(term == \"park_extra_magic_morning\") |>\n        pull(estimate)\n    )\n  ) |>\n  ggplot(aes(estimate)) +\n  geom_histogram(bins = 30, fill = \"#D55E00FF\", color = \"white\", alpha = 0.8) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-estimands_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\n3. Pull out the causal effect\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get t-based CIs\nboot_estimate <- int_t(ipw_results, boot_fits) |>\n  filter(term == \"park_extra_magic_morning\")\nboot_estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  term           .lower .estimate .upper .alpha .method\n  <chr>           <dbl>     <dbl>  <dbl>  <dbl> <chr>  \n1 park_extra_m… -0.0732      6.86   11.6   0.05 studen…\n```\n\n\n:::\n:::\n\n\nWe estimate that among days that have extra magic hours, the expected impact of having extra magic hours on the average posted wait time between 9 and 10am is 6.9 minutes, 95% CI (-0.1, 11.6). \n\n### The outcome model sandwich\n\nThere are two ways to get the sandwich estimator. The first is to use the same weighted outcome model as above along with the `{sandwich}` package. Using the `sandwich` function, we can get the robust estimate for the variance for the parameter of interest, as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sandwich)\nweighted_mod <- lm(\n  wait_minutes_posted_avg ~ park_extra_magic_morning,\n  data = seven_dwarfs_9_with_wt,\n  weights = w_att\n)\n\nsandwich(weighted_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         (Intercept)\n(Intercept)                    1.488\npark_extra_magic_morning      -1.488\n                         park_extra_magic_morning\n(Intercept)                                -1.488\npark_extra_magic_morning                    8.727\n```\n\n\n:::\n:::\n\n\nHere, our robust variance estimate is 8.727. We can then use this to construct a robust confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobust_var <- sandwich(weighted_mod)[2, 2]\npoint_est <- coef(weighted_mod)[2]\nlb <- point_est - 1.96 * sqrt(robust_var)\nub <- point_est + 1.96 * sqrt(robust_var)\nlb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npark_extra_magic_morning \n                  0.4383 \n```\n\n\n:::\n\n```{.r .cell-code}\nub\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npark_extra_magic_morning \n                   12.02 \n```\n\n\n:::\n:::\n\nWe estimate that among days that have extra magic hours, the expected impact of having extra magic hours on the average posted wait time between 9 and 10am is 6.2 minutes, 95% CI (0.4, 12). \n\nAlternatively, we could fit the model using the `{survey}` package. To do this, we need to create a design object, like we did when fitting weighted tables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survey)\n\ndes <- svydesign(\n  ids = ~1,\n  weights = ~w_att,\n  data = seven_dwarfs_9_with_wt\n)\n```\n:::\n\n\nThen we can use `svyglm` to fit the outcome model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsvyglm(wait_minutes_posted_avg ~ park_extra_magic_morning, des) |>\n  tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term  estimate std.error statistic   p.value conf.low\n  <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>\n1 (Int…    68.7       1.22     56.2  6.14e-178   66.3  \n2 park…     6.23      2.96      2.11 3.60e-  2    0.410\n# ℹ 1 more variable: conf.high <dbl>\n```\n\n\n:::\n:::\n\n### Sandwich estimator that takes into account the propensity score model\n\nThe correct sandwich estimator will also take into account the propensity score model. The `{PSW}` will allow us to do this. This package has some quirks, for example it doesn't work well with categorical variables, so we need to create dummy variables for `park_ticket_season` to pass into the model. *Actually, the code below isn't working because it seems there is a bug in the package. Stay tuned!*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PSW)\n\nseven_dwarfs_9 <- seven_dwarfs_9 |>\n  mutate(\n    park_ticket_season_regular = ifelse(park_ticket_season == \"regular\", 1, 0),\n    park_ticket_season_value = ifelse(park_ticket_season == \"value\", 1, 0)\n  )\npsw(\n  data = seven_dwarfs_9,\n  form.ps = \"park_extra_magic_morning ~ park_ticket_season_regular + park_ticket_season_value + park_close + park_temperature_high\",\n  weight = \"ATT\",\n  wt = TRUE,\n  out.var = \"wait_minutes_posted_avg\"\n)\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}