{
  "hash": "e2c72ab7733041ba5df9dc361cf199ed",
  "result": {
    "markdown": "# Target Trials and Standard Methods\n\n\n\n\n\n\n## Randomized trials {#sec-rand-trials}\n\nA *randomized trial* is one where the exposure (cause) of interest is *randomly assigned*.\n\n::: callout-note\nIn this book, we refer to analyses where the exposure is randomly assigned as a *randomized trial*, sometimes this is called an A/B test.\n:::\n\nWhy does randomization help?\nLooking at our assumptions in @sec-assump, randomized trials solve the well defined exposure portion of consistency by default -- the exposure is exactly what is randomized.\nLikewise for positivity; if we have randomly assigned folks to either the exposed or unexposed groups, we know the probability of assignment (and we know it is not exactly 0 or 1).\nRandomization alone does not solve the interference portion of consistency (for example, if we randomize some people to receive a vaccine for a communicable disease, their receiving it could lower the chance of those around them contracting the infectious disease because it changes the probability of exposure).\n*Ideal* randomized trials resolves the issue of exchangeability because the exposed and unexposed populations (in the limit) are inherently the same since their exposure status was determined by a random process (not by any factors that might make them different from each other).\nGreat!\nIn reality, we often see this assumption violated by issues such as *drop out* or *non-adherence* in randomized trials.\nIf there is differential drop out between exposure groups (for example, if participants randomly assigned to the treatment are more likely to drop out of a study, and thus we don't observe their outcome), then the observed exposure groups are no longer *exchangeable*.\nTherefore, in @tbl-assump-solved we have two columns, one for the *ideal* randomized trial (where adherence is assumed to be perfect and no participants drop out) and one for *realistic* randomized trials where this may not be so.\n\n| Assumption            | Ideal Randomized Trial | Realistic Randomized Trial | Observational Study  |\n|-----------------|-----------------|---------------------|-------------------|\n| Consistency (Well defined exposure) | 😄   | 😄       | 🤷 |\n| Consistency (No interference)       | 🤷   | 🤷       | 🤷 |\n| Positivity            | 😄   | 😄       | 🤷 |\n| Exchangeability       | 😄   | 🤷       | 🤷 |\n\n: Assumptions solved by study design. 😄 indicates it is solved by default, 🤷 indicates that it is *solvable* but not solved by default. {#tbl-assump-solved}\n\nWhen designing a study, the first step is asking an appropriate *causal question*. We then can map this question to a *protocol*, consisting of the following seven elements, as defined by @hernan2016using:\n\n* Eligibility criteria\n* Exposure definition\n* Assignment procedures\n* Follow-up period\n* Outcome definition\n* Causal contrast of interest\n* Analysis plan\n\nIn @tbl-protocol we map each of these elements to the corresponding assumption that it can address. For example, exchangeability can be addressed by the eligibility criteria (we can restrict our study to only participants for whom exposure assignment is exchangeable), assignment procedure (we could use random exposure assignment to ensure exchangeability), follow-up period (we can be sure to choose an appropriate start time for our follow-up period to ensure that we are not inducing bias -- we'll think more about this in a future chapter), and/or the analysis plan (we can adjust for any factors that would cause those in different exposure groups to lack exchangeability). \n\n<!-- TODO: link to the chapter where we talk about time zero? immortal time bias etc? is that now? -->\n\nAssumption | Eligibility Criteria | Exposure Definition| Assignment Procedures | Follow-up Period | Outcome Definition | Causal contrast | Analysis Plan\n------------|----------------- | ------------------|---------|----------|----------|--------- | -------\nConsistency (Well defined exposure) | |✔️|| | |\nConsistency (No interference) | | ✔️|✔️ | | ✔️ | | ✔️\nPositivity |✔️||✔️|| | | ✔️\nExchangeability |✔️||✔️|✔️|| | ✔️\n: Mapping assumptions to elements of a study protocol {#tbl-protocol}\n\nRecall our diagrams from @sec-diag (@fig-diagram-4); several of these protocol elements can be mapped to these diagrams when we are attempting to define our causal question.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Example diagram mapped to causal analysis terminology](chapter-04_files/figure-html/fig-diagram-4-1.png){#fig-diagram-4 width=672}\n:::\n:::\n\n\n\n## Target Trials\n\nThere are many reasons why randomization may not be possible. For example, it might not be ethical to randomly assign people to a particular exposure, there may not be funding available to run a randomized trial, or there might not be enough time to conduct a full trial. In these situations, we rely on observational data to help us answer causal questions by implementing a *target trial*. A *target trial* answers: What experiment would you design if you could? \n\n## Causal inference with `group_by()` and `summarize()` {#sec-group-sum}\n\nLet's suppose we are trying to estimate a causal effect of an exposure on an outcome, but the exposure is not *randomized*, in fact, there is a common cause of the exposure and outcome, making the exposed and unexposed groups *not exchangeable* without adjustment (violating the fourth assumption in @sec-assump).\n\n::: callout-note\nA **confounder** is a common cause of exposure and outcome.\n:::\n\n### One binary confounder\n\nLet's suppose this confounder is binary, see the simulation below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn <- 10000 \nsim <- tibble(\n  # generate the confounder from a binomial distribution\n  # with a probability 0.5 for being in either group \n  confounder = rbinom(n, 1, 0.5),\n  # make the probability of exposure dependent on the \n  # confounder value\n  p_exposure = case_when(\n    confounder == 1 ~ 0.75,\n    confounder == 0 ~ 0.25\n  ),\n  # generate the exposure from a binomial distribution\n  # with the probability of exposure dependent on the confounder\n  exposure = rbinom(n, 1, p_exposure),\n  # generate the \"true\" average treatment effect of 0 \n  # to do this, we are going to generate the potential outcomes, first \n  # the potential outcome if exposure = 0\n  # (notice exposure is not in the equation below, only the confounder)\n  # we use rnorm(n) to add the random error term that is normally\n  # distributed with a mean of 0 and a standard deviation of 1\n  y0 = confounder + rnorm(n),\n  # because the true effect is 0, the potential outcome if exposure = 1\n  # is identical\n  y1 = y0,\n  # now, in practice we will only see one of these, outcome is what is \n  # observed\n  outcome = (1 - exposure) * y0 + exposure * y1,\n  observed_potential_outcome = case_when(\n    exposure == 0 ~ \"y0\",\n    exposure == 1 ~ \"y1\"\n  )\n)\n```\n:::\n\n\nHere we have one binary `confounder`, the probability that `confounder = 1` is `0.5`.\nThe probability of the being exposed is `0.75` for those for whom `confounder = 1` `0.25` for those for whom `confounder = 0`.\nThere is no effect of the `exposure` on the `outcome` (the true causal effect is 0); the `outcome` effect is fully dependent on the `confounder`. In this simulation we generate the potential outcomes to drive home our assumptions; many of our simulations in this book will skip this step.\nLet's look at this generated data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim |>\n  select(confounder, exposure, outcome, observed_potential_outcome)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10,000 × 4\n   confounder exposure outcome observed_potential_out…¹\n        <int>    <int>   <dbl> <chr>                   \n 1          0        0 -0.804  y0                      \n 2          0        0 -1.06   y0                      \n 3          1        1 -0.0354 y1                      \n 4          1        1 -0.186  y1                      \n 5          0        0 -0.500  y0                      \n 6          1        1  0.475  y1                      \n 7          1        0  0.698  y0                      \n 8          1        0  1.47   y0                      \n 9          1        0  0.752  y0                      \n10          0        0  1.26   y0                      \n# ℹ 9,990 more rows\n# ℹ abbreviated name: ¹​observed_potential_outcome\n```\n\n\n:::\n:::\n\n\nGreat! Let's begin by proving to ourselves that this violates the exchangeability assumption. Recall from @sec-assump:\n\n> **Exchangeability**: We assume that within levels of relevant variables (confounders), exposed and unexposed subjects have an equal likelihood of experiencing any outcome prior to exposure; i.e. the exposed and unexposed subjects are exchangeable. This assumption is sometimes referred to as **no unmeasured confounding**.\n\nNow, let's try to estimate the effect of the `exposure` on the `outcome` assuming the two exposed groups are exchangeable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim |>\n  group_by(exposure) |>\n  summarise(avg_outcome = mean(outcome))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  exposure avg_outcome\n     <int>       <dbl>\n1        0       0.228\n2        1       0.756\n```\n\n\n:::\n:::\n\n\nThe average outcome among the exposed is `0.76` and among the unexposed `0.23`, yielding an average effect of the exposure of `0.76-0.23=0.53`.\nLet's do a little R work to get there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim |>\n  group_by(exposure) |>\n  summarise(avg_outcome = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure, \n    values_from = avg_outcome,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  estimate\n     <dbl>\n1    0.528\n```\n\n\n:::\n:::\n\n\nOk, so assuming the exposure groups are exchangeable (and assuming the rest of the assumptions from @sec-assump hold), we estimate the effect of the exposure on the outcome to be 0.53.\nWe *know* the exchaneability assumption is violated based on how we simulated the data.\nHow can we estimate an unbiased effect?\nThe easiest way to do so is to estimate the effect within each confounder class.\nThis will work because folks with the same value of the confounder have an equal probability of exposure.\nInstead of just grouping by the exposure, let's group by the confounder as well:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim |>\n  group_by(confounder, exposure) |>\n  summarise(avg_outcome = mean(outcome))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n# Groups:   confounder [2]\n  confounder exposure avg_outcome\n       <int>    <int>       <dbl>\n1          0        0    -0.0185 \n2          0        1     0.00954\n3          1        0     0.994  \n4          1        1     1.01   \n```\n\n\n:::\n:::\n\n\nWe can now calculate the average effect within each confounder class as well as the overall causal effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Average effect within each confounder class\nsim |>\n  group_by(confounder, exposure) |>\n  summarise(avg_outcome = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure, \n    values_from = avg_outcome,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  confounder estimate\n       <int>    <dbl>\n1          0   0.0280\n2          1   0.0122\n```\n\n\n:::\n\n```{.r .cell-code}\n## Overall average effect\n\nsim |>\n  group_by(confounder, exposure) |>\n  summarise(avg_outcome = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure, \n    values_from = avg_outcome,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) |>\n  summarise(mean(estimate)) # note, we would need to weight this if the confounder groups were not equal sized\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  `mean(estimate)`\n             <dbl>\n1           0.0201\n```\n\n\n:::\n:::\n\n\nGreat!\nNow our estimate is much closer to the true value (0).\n\n::: callout\nThe method we are using to solve the fact that our two groups are not exchangeable is known as **stratification**. We are *stratifying* by the confounder(s) and estimating the causal effect within each stratum. To get an overall average causal effect we are averaging across the strata. This can be a great tool if there are very few confounders, however it can suffer from the curse of dimensionality as the number of confounders as well as the number of levels within each confounder increases.\n:::\n\n### Two binary confounders\n\nLet's extend this to two binary confounders.\nThe simulation below now has two binary confounders.\nThe true causal effect of the `exposure` on the `outcome` is still 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn <- 10000\nsim2 <- tibble(\n  confounder_1 = rbinom(n, 1, 0.5),\n  confounder_2 = rbinom(n, 1, 0.5), \n  \n  p_exposure = case_when(\n    confounder_1 == 1 & confounder_2 == 1 ~ 0.75,\n    confounder_1 == 0 & confounder_2 == 1 ~ 0.9,\n    confounder_1 == 1 & confounder_2 == 0 ~ 0.2,\n    confounder_1 == 0 & confounder_2 == 0 ~ 0.1,\n  ),\n  exposure = rbinom(n, 1, p_exposure),\n  outcome = confounder_1 + confounder_2 + rnorm(n) \n)\n```\n:::\n\n\nNow we are going to group by both confounders and estimate the causal effect within each stratum.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim2 |>\n  group_by(confounder_1, confounder_2, exposure) |>\n  summarise(avg_y = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure,\n    values_from = avg_y,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n# Groups:   confounder_1 [2]\n  confounder_1 confounder_2 estimate\n         <int>        <int>    <dbl>\n1            0            0  -0.122 \n2            0            1   0.0493\n3            1            0   0.0263\n4            1            1   0.0226\n```\n\n\n:::\n:::\n\n\nWe can also estimate the overall causal effect:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim2 |>\n  group_by(confounder_1, confounder_2, exposure) |>\n  summarise(avg_outcome = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure, \n    values_from = avg_outcome,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0, .groups = \"drop\") |>\n  summarise(mean(estimate)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  `mean(estimate)`\n             <dbl>\n1         -0.00594\n```\n\n\n:::\n:::\n\n\n### Continuous confounder\n\nSo far our strategy has been to estimate the causal effect within strata where the individuals are *exchangeable*.\nHow could we extend this to a continuous confounder?\nLet's create another simulation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn <- 10000 \nsim3 <- tibble(\n  confounder = rnorm(n), \n  p_exposure = exp(confounder) / (1 + exp(confounder)),\n  exposure = rbinom(n, 1, p_exposure),\n  outcome = confounder + rnorm(n) \n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsim3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10,000 × 4\n   confounder p_exposure exposure outcome\n        <dbl>      <dbl>    <int>   <dbl>\n 1     -0.626      0.348        0 -0.840 \n 2      0.184      0.546        1  0.0769\n 3     -0.836      0.302        0 -1.30  \n 4      1.60       0.831        1  0.911 \n 5      0.330      0.582        1 -0.461 \n 6     -0.820      0.306        0 -1.16  \n 7      0.487      0.620        1 -0.780 \n 8      0.738      0.677        1 -0.656 \n 9      0.576      0.640        1  0.995 \n10     -0.305      0.424        0  2.91  \n# ℹ 9,990 more rows\n```\n\n\n:::\n:::\n\n\nIf we want to still use `group_by` and `summarise`, we could bin the continuous confounder, for example using it's quintiles, and estimate the causal effect within each bin:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim3 |>\n  mutate(confounder_q = ntile(confounder, 5)) |>\n  group_by(confounder_q, exposure) |>\n  summarise(avg_y = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure,\n    values_from = avg_y,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  confounder_q estimate\n         <int>    <dbl>\n1            1   0.237 \n2            2   0.0622\n3            3   0.0264\n4            4   0.133 \n5            5   0.178 \n```\n\n\n:::\n\n```{.r .cell-code}\nsim3 |>\n  mutate(confounder_q = ntile(confounder, 5)) |>\n  group_by(confounder_q, exposure) |>\n  summarise(avg_y = mean(outcome)) |>\n  pivot_wider(\n    names_from = exposure,\n    values_from = avg_y,  \n    names_prefix = \"x_\"\n  ) |>\n  summarise(estimate = x_1 - x_0) |>\n  summarise(estimate = mean(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  estimate\n     <dbl>\n1    0.127\n```\n\n\n:::\n:::\n\n\nGreat!\nNow, in practice we have many more than one or two binary confounders, we often have many many confounders, both continuous and binary.\nAttempting to estimate the causal effect within each unique stratum would be very inefficient (and often not possible!).\nWhat if instead we could create a single summary score for all of the confounders?\nHold onto this thought, we'll bring it up again when we introduce *propensity scores*.\n\n## When do standard methods succeed and fail? {#sec-standard}\n\nWhen teaching these topics, we are often asked when \"standard methods\" will succeed, i.e.: when can we just fit a linear regression model to estimate a causal effect?\nLet's start with the easiest example: the exposure is *randomized*.\nAs discussed in @sec-rand-trials, randomization ensures comparability and can simplify the methods needed to estimate a causal effect.\nIn the presence of a randomized exposure (assuming perfect adherence to the exposure assigned, no one dropped out of the study, etc.), simple tools like regression can be used to estimate a causal effect.\n\n### When correlation is causation\n\nWhen you have no confounders and there is a linear relationship between the exposure and the outcome, that *correlation is a causal relationship*.\nEven in these cases, using the methods you will learn in this book can help.\n\n1.  Adjusting for baseline covariates can make an estimate *more efficient*\n2.  Propensity score weighting is *more efficient* that direct adjustment\n3.  Sometimes we are *more comfortable with the functional form of the propensity score* (predicting exposure) than the outcome model\n\nLet's look at an example.\nI am going to simulate 100 observations.\nHere the treatment is randomly assigned and there are two baseline covariates: `age` and `weight`.\nOn average, the treatment causes a one unit increase in the outcome (this is called the *average treatment effect*, we will talk more about this quantity in future chapters).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(10)\nn <- 100\nd <- tibble(\n  age = rnorm(n, 55, 20),\n  weight = rnorm(n),\n  # generate the treatment from a binomial distribution\n  # with the probability of treatment = 0.5\n  treatment = rbinom(n, 1, 0.5),\n  # generate the average causal effect of treatment: 1\n  y = 1 * treatment + 0.2 * age + 0.2 * weight + rnorm(n)\n)\n```\n:::\n\n\nWe can draw a causal diagram of the relationship described in the code above (@fig-diag).\n@sec-dags contains more information on these causal diagrams, but briefly, the arrows denote causal relationships, so since we have established that the treatment causes an increase in the outcome (an average treatment effect of 1), we see an arrow from `trt` to `y` in this diagram.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Causal Diagram of Example Randomized Study](chapter-04_files/figure-html/fig-diag-1.png){#fig-diag width=672}\n:::\n:::\n\n\nLet's examine three models: (1) an unadjusted model (@tbl-panel-1), (2) a linear model that adjusts for the baseline covariates (@tbl-panel-2), and (3) a propensity score weighted model (@tbl-panel-3).\n\n::: {#tbl-panel layout-ncol=\"2\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(gtsummary)\nlm(y ~ treatment, d) |>\n  tbl_regression() |>\n  modify_column_unhide(column = std.error) |>\n  modify_caption(\"Unadjusted regression\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dnecmmlmpz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#dnecmmlmpz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dnecmmlmpz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dnecmmlmpz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dnecmmlmpz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dnecmmlmpz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dnecmmlmpz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dnecmmlmpz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dnecmmlmpz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dnecmmlmpz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dnecmmlmpz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dnecmmlmpz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dnecmmlmpz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dnecmmlmpz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dnecmmlmpz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dnecmmlmpz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dnecmmlmpz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dnecmmlmpz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dnecmmlmpz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dnecmmlmpz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dnecmmlmpz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dnecmmlmpz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dnecmmlmpz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dnecmmlmpz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dnecmmlmpz .gt_left {\n  text-align: left;\n}\n\n#dnecmmlmpz .gt_center {\n  text-align: center;\n}\n\n#dnecmmlmpz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dnecmmlmpz .gt_font_normal {\n  font-weight: normal;\n}\n\n#dnecmmlmpz .gt_font_bold {\n  font-weight: bold;\n}\n\n#dnecmmlmpz .gt_font_italic {\n  font-style: italic;\n}\n\n#dnecmmlmpz .gt_super {\n  font-size: 65%;\n}\n\n#dnecmmlmpz .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#dnecmmlmpz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dnecmmlmpz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dnecmmlmpz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dnecmmlmpz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dnecmmlmpz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dnecmmlmpz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <caption>Unadjusted regression</caption>\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;SE&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>SE</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>95% CI</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.93</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.803</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.66, 2.5</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.2</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><sup class=\"gt_footnote_marks\">1</sup> SE = Standard Error, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm(y ~ treatment + age + weight, d) |>\n  tbl_regression() |>\n  modify_column_unhide(column = std.error) |>\n  modify_caption(\"Adjusted regression\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qepoxygcps\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#qepoxygcps .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qepoxygcps .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qepoxygcps .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qepoxygcps .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qepoxygcps .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qepoxygcps .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qepoxygcps .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qepoxygcps .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qepoxygcps .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qepoxygcps .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qepoxygcps .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qepoxygcps .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qepoxygcps .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qepoxygcps .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qepoxygcps .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qepoxygcps .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qepoxygcps .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qepoxygcps .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qepoxygcps .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qepoxygcps .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qepoxygcps .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qepoxygcps .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qepoxygcps .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qepoxygcps .gt_left {\n  text-align: left;\n}\n\n#qepoxygcps .gt_center {\n  text-align: center;\n}\n\n#qepoxygcps .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qepoxygcps .gt_font_normal {\n  font-weight: normal;\n}\n\n#qepoxygcps .gt_font_bold {\n  font-weight: bold;\n}\n\n#qepoxygcps .gt_font_italic {\n  font-style: italic;\n}\n\n#qepoxygcps .gt_super {\n  font-size: 65%;\n}\n\n#qepoxygcps .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#qepoxygcps .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qepoxygcps .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qepoxygcps .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qepoxygcps .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qepoxygcps .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qepoxygcps .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <caption>Adjusted regression</caption>\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;SE&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>SE</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>95% CI</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.0</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.204</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.59, 1.4</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.20</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.005</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.19, 0.22</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.34</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.106</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.13, 0.55</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><sup class=\"gt_footnote_marks\">1</sup> SE = Standard Error, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nd |>\n  mutate(\n    p = glm(treatment ~ weight + age, data = d) |> predict(type = \"response\"),\n    ate = treatment / p + (1 - treatment) / (1 - p)\n  ) |>\n  as.data.frame() -> d\nlibrary(PSW)\ndf <- as.data.frame(d)\nx <- psw(df, \n         \"treatment ~ weight + age\", \n         weight = \"ATE\", wt = TRUE,\n         out.var = \"y\")\ntibble(\n  Characteristic = \"treatment\",\n  Beta = round(x$est.wt, 1),\n  SE = round(x$std.wt, 3),\n  `95% CI` = glue::glue(\"{round(x$est.wt - 1.96 * x$std.wt, 1)}, {round(x$est.wt + 1.96 * x$std.wt, 1)}\"),\n  `p-value` = \"<0.001\"\n) |>\n  knitr::kable(caption = \"Propensity score weighted regression\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Propensity score weighted regression\n\n|Characteristic | Beta|    SE|95% CI   |p-value |\n|:--------------|----:|-----:|:--------|:-------|\n|treatment      |    1| 0.202|0.6, 1.4 |<0.001  |\n\n\n:::\n:::\n\n\nThree ways to estimate the causal effect.\n:::\n\nLooking at the three outputs in @tbl-panel, we can first notice that all three are \"unbiased\" estimates of the causal effect (we know the true average treatment effect is 1, based on our simulation) -- the estimated causal effect in each table is in the `Beta` column.\nGreat, so all methods give us an unbiased estimate.\nNext, let's look at the `SE` (standard error) column along with the `95% CI` (confidence interval) column.\nNotice the unadjusted model has a *wider* confidence interval (in fact, in this case the confidence interval includes the null, 0) -- this means if we were to use this method, even though we were able to estimate an unbiased causal effect, we would often conclude that we *fail to reject the null* that relationship between the treatment and outcome is 0.\nIn statistical terms, we refer to this as a *lack of efficiency*.\nLooking at the adjusted analysis in @tbl-panel-2, we see that the standard error is quite a bit smaller (and likewise the confidence interval is tighter, no longer including the null).\nEven though our baseline covariates `age` and `weight` were not *confounders* adjusting from them *increased the precision* of our result (this is a good thing! We want estimates that are both unbiased *and* precise).\nFinally, looking at the propensity score weighted estimate we can see that our precision was slightly improved compared to the adjusted result (0.202 compared to 0.204).\nThe magnitude of this improvement will depend on several factors, but it has been shown mathematically that using propensity scores like this to adjust for baseline factors in a randomized trial will *always* improve precision [@williamson2014variance].\nWhat can we learn from this small demonstration?\nEven in the perfect scenario, where we can estimate unbiased results without using propensity scores, the methods we will show here can be useful.\nThe utility of these methods only increases when exploring more complex examples, such as situations where the effect is *not* randomized, the introduction of time-varying confounders, etc.\n\nWhat if we did not have a randomized exposure?\nThere are many cases where randomization to a treatment is not ethical or feasible.\nStandard methods can still estimate unbiased effects, but more care needs to be given to the previously mentioned assumptions (@tbl-assump-solved).\nFor example, we need the exposed an unexposed groups to be *exchangeable*; this means we must adjust for *all confounders* with their correct functional form.\nIf everything is simple and linear (and there is no effect heterogeneity, that is everyone's causal effect is the same regardless of their baseline factors), then a simple regression model that adjusts for the confounders can give you an unbiased result.\nLet's look at a simple example such as this.\nNotice in the simulation below, the main difference compared to the above simulation is that the probability of treatment assignment is no longer 0.5 as it was above, but now dependent on the participants `age` and `weight`. For example, maybe doctors tend to prescribe a certain treatment to patients who are older and who weigh more.\nThe true causal effect is still 1, but now we have two confounders, `age` and `weight` (@fig-diag-2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn <- 100000\nd <- tibble(\n  age = rnorm(n, 55, 20),\n  weight = rnorm(n),\n  # generate the treatment from a binomial distribution\n  # with the probability of treatment dependent on the age and weight\n  treatment = rbinom(n, 1, 1 / (1 + exp(-0.01 * age - weight))),\n  ## generate the true average causal effect of the treatment: 1\n  y = 1 * treatment + 0.2 * age + 0.2 * weight + rnorm(n)\n)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Causal Diagram of Example Observation Study](chapter-04_files/figure-html/fig-diag-2-1.png){#fig-diag-2 width=672}\n:::\n:::\n\n\n::: {#tbl-panel-2 layout-ncol=\"2\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm(y ~ treatment, d) |>\n  tbl_regression() |>\n  modify_column_unhide(column = std.error) |>\n  modify_caption(\"Unadjusted regression\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lfkdhkjrur\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#lfkdhkjrur .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lfkdhkjrur .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lfkdhkjrur .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lfkdhkjrur .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lfkdhkjrur .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lfkdhkjrur .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lfkdhkjrur .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lfkdhkjrur .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lfkdhkjrur .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lfkdhkjrur .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lfkdhkjrur .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lfkdhkjrur .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lfkdhkjrur .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lfkdhkjrur .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfkdhkjrur .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lfkdhkjrur .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lfkdhkjrur .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfkdhkjrur .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lfkdhkjrur .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfkdhkjrur .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lfkdhkjrur .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfkdhkjrur .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lfkdhkjrur .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfkdhkjrur .gt_left {\n  text-align: left;\n}\n\n#lfkdhkjrur .gt_center {\n  text-align: center;\n}\n\n#lfkdhkjrur .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lfkdhkjrur .gt_font_normal {\n  font-weight: normal;\n}\n\n#lfkdhkjrur .gt_font_bold {\n  font-weight: bold;\n}\n\n#lfkdhkjrur .gt_font_italic {\n  font-style: italic;\n}\n\n#lfkdhkjrur .gt_super {\n  font-size: 65%;\n}\n\n#lfkdhkjrur .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#lfkdhkjrur .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lfkdhkjrur .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lfkdhkjrur .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lfkdhkjrur .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lfkdhkjrur .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lfkdhkjrur .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <caption>Unadjusted regression</caption>\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;SE&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>SE</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>95% CI</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.8</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.027</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.8, 1.9</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><sup class=\"gt_footnote_marks\">1</sup> SE = Standard Error, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm(y ~ treatment + age + weight, d) |>\n  tbl_regression() |>\n  modify_column_unhide(column = std.error) |>\n  modify_caption(\"Adjusted regression\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yiyqgqwbps\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#yiyqgqwbps .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yiyqgqwbps .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yiyqgqwbps .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yiyqgqwbps .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yiyqgqwbps .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yiyqgqwbps .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yiyqgqwbps .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yiyqgqwbps .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yiyqgqwbps .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yiyqgqwbps .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yiyqgqwbps .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yiyqgqwbps .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yiyqgqwbps .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yiyqgqwbps .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yiyqgqwbps .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yiyqgqwbps .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yiyqgqwbps .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yiyqgqwbps .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yiyqgqwbps .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yiyqgqwbps .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yiyqgqwbps .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yiyqgqwbps .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yiyqgqwbps .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yiyqgqwbps .gt_left {\n  text-align: left;\n}\n\n#yiyqgqwbps .gt_center {\n  text-align: center;\n}\n\n#yiyqgqwbps .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yiyqgqwbps .gt_font_normal {\n  font-weight: normal;\n}\n\n#yiyqgqwbps .gt_font_bold {\n  font-weight: bold;\n}\n\n#yiyqgqwbps .gt_font_italic {\n  font-style: italic;\n}\n\n#yiyqgqwbps .gt_super {\n  font-size: 65%;\n}\n\n#yiyqgqwbps .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#yiyqgqwbps .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yiyqgqwbps .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yiyqgqwbps .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yiyqgqwbps .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yiyqgqwbps .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yiyqgqwbps .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <caption>Adjusted regression</caption>\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;SE&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>SE</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>95% CI</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.99</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.007</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.98, 1.0</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.20</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.000</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.20, 0.20</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.20</td>\n<td headers=\"std.error\" class=\"gt_row gt_center\">0.003</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.20, 0.21</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><sup class=\"gt_footnote_marks\">1</sup> SE = Standard Error, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nd |>\n  mutate(\n    p = glm(treatment ~ weight + age, data = d, family = binomial) |> predict(type = \"response\"),\n    ate = treatment / p + (1 - treatment) / (1 - p)\n  ) |>\n  as.data.frame() -> d\nlibrary(PSW)\ndf <- as.data.frame(d)\nx <- psw(df, \n         \"treatment ~ weight + age\", \n         weight = \"ATE\", wt = TRUE,\n         out.var = \"y\")\ntibble(\n  Characteristic = \"treatment\",\n  Beta = round(x$est.wt, 1),\n  SE = round(x$std.wt, 3),\n  `95% CI` = glue::glue(\"{round(x$est.wt - 1.96 * x$std.wt, 1)}, {round(x$est.wt + 1.96 * x$std.wt, 1)}\"),\n  `p-value` = \"<0.001\"\n) |>\n  knitr::kable(caption = \"Propensity score weighted regression\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Propensity score weighted regression\n\n|Characteristic | Beta|    SE|95% CI |p-value |\n|:--------------|----:|-----:|:------|:-------|\n|treatment      |    1| 0.014|1, 1   |<0.001  |\n\n\n:::\n:::\n\n\nThree ways to estimate a causal effect in a non-randomized setting\n:::\n\nFirst, let's look at @tbl-panel-2-1.\nHere, we see that the unadjusted effect is *biased* (it differs from the true effect, 1, and the true effect is *not* contained in the reported 95% confidence interval).\nNow lets compare @tbl-panel-2-2 and @tbl-panel-2-3.\nTechnically, both are estimating unbiased causal effects.\nThe output in the `Beta` column of @tbl-panel-2-2 is technically a *conditional* effect (and often in causal inference we want marginal effects), but because there is no treatment heterogeneity in this simulation, the conditional and marginal effects are equal.\n@tbl-panel-2-3, using the propensity score, also estimates an unbiased effect, but it is no longer the most *efficient* (that was true when the baseline covariates were merely causal for `y`, now that they are `confounders` the efficiency gains for using propensity score weighting are not as clear cut).\nSo why would we ever use propensity scores in this case?\nSometimes we have a better understanding of the functional form of the propensity score model compared to the outcome model.\nAlternatively, sometimes the outcome model is difficult to fit (for example, if the outcome is rare).\n\n::: callout-tip\n## Marginal versus conditional effects\n\nIn causal inference, we are often interested in *marginal* effects, mathematically, this means that we want to *marginalize* the effect of interest across the distribution of factors in a particular population that we are trying to estimate a causal effect for.\nIn an adjusted regression model, the coefficients are *conditional*, in other words, when describing the estimated coefficient, we often say something like \"a one-unit change in the exposure results in a `coefficient` change in the outcome *holding all other variables in the model constant*. In the case where the outcome is continuous, the effect is linear, and there are no interactions between the exposure effect and other factors about the population, the distinction between an conditional and a marginal effect is largely semantic. If there *is* an interaction in the model, that is, if the exposure has a different impact on the outcome depending on some other factor, we no longer have a single coefficient to interpret. We would want to estimate a *marginal* effect, taking into account the distribution of that factor in the population of interest. Why? We are ultimately trying to determine whether we should suggest the exposure to the target population, so we want to know *on average* whether it will be beneficial. Let's look at quick example: suppose that you are designing an online shopping site. Currently, the\"Purchase\" button is grey. Changing the button to red increases revenue by \\$10 for people who are *not* colorblind and decreases revenue by \\$10 for those who *are* colorblind -- *the effect is heterogeneous*. Whether you change the color of the button will depend on the *distribution* of colorblind folks that visit your website. For example, if 50% of the visitors are colorblind, your average effect of changing the color would be \\$0. If instead, 100% are colorblind, the average effect of changing the color would be -\\$10. Likewise, if 0% are colorblind, the average effect of changing the color to red would be \\$10. Your decision, therefore, needs to be based on the *marginal* effect, the effect that takes into account the distribution of colorblind online customers.\n:::\n",
    "supporting": [
      "chapter-04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}